// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


enum BodyMeasurementTypeMsg {
  weight,
  height,
  bodyFat,
}

/// Raw Health Connect availability signals, mapped to the Dart
/// `HealthConnectAvailability` enum on the Flutter side. Kept as separate
/// signals (rather than a native enum) so the enum stays a single source of
/// truth in Dart.
class HealthConnectAvailabilityDetail {
  HealthConnectAvailabilityDetail({
    required this.sdkStatus,
    required this.unsupportedProfile,
    required this.standaloneNeedsPlayStore,
  });

  /// Raw `HealthConnectClient.getSdkStatus` int.
  int sdkStatus;

  /// True when running in a work/managed profile where Health Connect is
  /// unsupported (Android 13+).
  bool unsupportedProfile;

  /// True when the standalone Health Connect APK is installed on Android 13-
  /// but the Play Store is not (so it can never be updated).
  bool standaloneNeedsPlayStore;

  List<Object?> _toList() {
    return <Object?>[
      sdkStatus,
      unsupportedProfile,
      standaloneNeedsPlayStore,
    ];
  }

  Object encode() {
    return _toList();  }

  static HealthConnectAvailabilityDetail decode(Object result) {
    result as List<Object?>;
    return HealthConnectAvailabilityDetail(
      sdkStatus: result[0]! as int,
      unsupportedProfile: result[1]! as bool,
      standaloneNeedsPlayStore: result[2]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HealthConnectAvailabilityDetail || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sdkStatus, other.sdkStatus) && _deepEquals(unsupportedProfile, other.unsupportedProfile) && _deepEquals(standaloneNeedsPlayStore, other.standaloneNeedsPlayStore);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'HealthConnectAvailabilityDetail(sdkStatus: $sdkStatus, unsupportedProfile: $unsupportedProfile, standaloneNeedsPlayStore: $standaloneNeedsPlayStore)';
  }
}

class WeightEntryMsg {
  WeightEntryMsg({
    required this.timeEpochMs,
    required this.weightKg,
    required this.source,
    required this.id,
    required this.isOpenVitalsEntry,
  });

  int timeEpochMs;

  double weightKg;

  String source;

  String id;

  bool isOpenVitalsEntry;

  List<Object?> _toList() {
    return <Object?>[
      timeEpochMs,
      weightKg,
      source,
      id,
      isOpenVitalsEntry,
    ];
  }

  Object encode() {
    return _toList();  }

  static WeightEntryMsg decode(Object result) {
    result as List<Object?>;
    return WeightEntryMsg(
      timeEpochMs: result[0]! as int,
      weightKg: result[1]! as double,
      source: result[2]! as String,
      id: result[3]! as String,
      isOpenVitalsEntry: result[4]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WeightEntryMsg || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(timeEpochMs, other.timeEpochMs) && _deepEquals(weightKg, other.weightKg) && _deepEquals(source, other.source) && _deepEquals(id, other.id) && _deepEquals(isOpenVitalsEntry, other.isOpenVitalsEntry);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'WeightEntryMsg(timeEpochMs: $timeEpochMs, weightKg: $weightKg, source: $source, id: $id, isOpenVitalsEntry: $isOpenVitalsEntry)';
  }
}

class HeightEntryMsg {
  HeightEntryMsg({
    required this.timeEpochMs,
    required this.heightCm,
    required this.source,
    required this.id,
    required this.isOpenVitalsEntry,
  });

  int timeEpochMs;

  double heightCm;

  String source;

  String id;

  bool isOpenVitalsEntry;

  List<Object?> _toList() {
    return <Object?>[
      timeEpochMs,
      heightCm,
      source,
      id,
      isOpenVitalsEntry,
    ];
  }

  Object encode() {
    return _toList();  }

  static HeightEntryMsg decode(Object result) {
    result as List<Object?>;
    return HeightEntryMsg(
      timeEpochMs: result[0]! as int,
      heightCm: result[1]! as double,
      source: result[2]! as String,
      id: result[3]! as String,
      isOpenVitalsEntry: result[4]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HeightEntryMsg || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(timeEpochMs, other.timeEpochMs) && _deepEquals(heightCm, other.heightCm) && _deepEquals(source, other.source) && _deepEquals(id, other.id) && _deepEquals(isOpenVitalsEntry, other.isOpenVitalsEntry);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'HeightEntryMsg(timeEpochMs: $timeEpochMs, heightCm: $heightCm, source: $source, id: $id, isOpenVitalsEntry: $isOpenVitalsEntry)';
  }
}

class BodyFatEntryMsg {
  BodyFatEntryMsg({
    required this.timeEpochMs,
    required this.percent,
    required this.source,
    required this.id,
    required this.isOpenVitalsEntry,
  });

  int timeEpochMs;

  double percent;

  String source;

  String id;

  bool isOpenVitalsEntry;

  List<Object?> _toList() {
    return <Object?>[
      timeEpochMs,
      percent,
      source,
      id,
      isOpenVitalsEntry,
    ];
  }

  Object encode() {
    return _toList();  }

  static BodyFatEntryMsg decode(Object result) {
    result as List<Object?>;
    return BodyFatEntryMsg(
      timeEpochMs: result[0]! as int,
      percent: result[1]! as double,
      source: result[2]! as String,
      id: result[3]! as String,
      isOpenVitalsEntry: result[4]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BodyFatEntryMsg || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(timeEpochMs, other.timeEpochMs) && _deepEquals(percent, other.percent) && _deepEquals(source, other.source) && _deepEquals(id, other.id) && _deepEquals(isOpenVitalsEntry, other.isOpenVitalsEntry);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'BodyFatEntryMsg(timeEpochMs: $timeEpochMs, percent: $percent, source: $source, id: $id, isOpenVitalsEntry: $isOpenVitalsEntry)';
  }
}

/// Shared shape for LeanBodyMass / BoneMass / BodyWaterMass entries.
class BodyMassEntryMsg {
  BodyMassEntryMsg({
    required this.timeEpochMs,
    required this.massKg,
    required this.source,
  });

  int timeEpochMs;

  double massKg;

  String source;

  List<Object?> _toList() {
    return <Object?>[
      timeEpochMs,
      massKg,
      source,
    ];
  }

  Object encode() {
    return _toList();  }

  static BodyMassEntryMsg decode(Object result) {
    result as List<Object?>;
    return BodyMassEntryMsg(
      timeEpochMs: result[0]! as int,
      massKg: result[1]! as double,
      source: result[2]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BodyMassEntryMsg || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(timeEpochMs, other.timeEpochMs) && _deepEquals(massKg, other.massKg) && _deepEquals(source, other.source);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'BodyMassEntryMsg(timeEpochMs: $timeEpochMs, massKg: $massKg, source: $source)';
  }
}

class BmrEntryMsg {
  BmrEntryMsg({
    required this.timeEpochMs,
    required this.kcalPerDay,
    required this.source,
  });

  int timeEpochMs;

  double kcalPerDay;

  String source;

  List<Object?> _toList() {
    return <Object?>[
      timeEpochMs,
      kcalPerDay,
      source,
    ];
  }

  Object encode() {
    return _toList();  }

  static BmrEntryMsg decode(Object result) {
    result as List<Object?>;
    return BmrEntryMsg(
      timeEpochMs: result[0]! as int,
      kcalPerDay: result[1]! as double,
      source: result[2]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BmrEntryMsg || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(timeEpochMs, other.timeEpochMs) && _deepEquals(kcalPerDay, other.kcalPerDay) && _deepEquals(source, other.source);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'BmrEntryMsg(timeEpochMs: $timeEpochMs, kcalPerDay: $kcalPerDay, source: $source)';
  }
}

class BodyMeasurementEntryMsg {
  BodyMeasurementEntryMsg({
    required this.id,
    required this.type,
    required this.timeEpochMs,
    required this.value,
    required this.source,
    required this.isOpenVitalsEntry,
  });

  String id;

  BodyMeasurementTypeMsg type;

  int timeEpochMs;

  double value;

  String source;

  bool isOpenVitalsEntry;

  List<Object?> _toList() {
    return <Object?>[
      id,
      type,
      timeEpochMs,
      value,
      source,
      isOpenVitalsEntry,
    ];
  }

  Object encode() {
    return _toList();  }

  static BodyMeasurementEntryMsg decode(Object result) {
    result as List<Object?>;
    return BodyMeasurementEntryMsg(
      id: result[0]! as String,
      type: result[1]! as BodyMeasurementTypeMsg,
      timeEpochMs: result[2]! as int,
      value: result[3]! as double,
      source: result[4]! as String,
      isOpenVitalsEntry: result[5]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BodyMeasurementEntryMsg || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) && _deepEquals(type, other.type) && _deepEquals(timeEpochMs, other.timeEpochMs) && _deepEquals(value, other.value) && _deepEquals(source, other.source) && _deepEquals(isOpenVitalsEntry, other.isOpenVitalsEntry);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'BodyMeasurementEntryMsg(id: $id, type: $type, timeEpochMs: $timeEpochMs, value: $value, source: $source, isOpenVitalsEntry: $isOpenVitalsEntry)';
  }
}

class BodyMeasurementWriteRequestMsg {
  BodyMeasurementWriteRequestMsg({
    required this.type,
    required this.timeEpochMs,
    required this.value,
  });

  BodyMeasurementTypeMsg type;

  int timeEpochMs;

  double value;

  List<Object?> _toList() {
    return <Object?>[
      type,
      timeEpochMs,
      value,
    ];
  }

  Object encode() {
    return _toList();  }

  static BodyMeasurementWriteRequestMsg decode(Object result) {
    result as List<Object?>;
    return BodyMeasurementWriteRequestMsg(
      type: result[0]! as BodyMeasurementTypeMsg,
      timeEpochMs: result[1]! as int,
      value: result[2]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BodyMeasurementWriteRequestMsg || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(type, other.type) && _deepEquals(timeEpochMs, other.timeEpochMs) && _deepEquals(value, other.value);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'BodyMeasurementWriteRequestMsg(type: $type, timeEpochMs: $timeEpochMs, value: $value)';
  }
}

class HydrationEntryMsg {
  HydrationEntryMsg({
    required this.startEpochMs,
    required this.endEpochMs,
    required this.liters,
    required this.source,
    required this.id,
    this.clientRecordId,
    required this.isOpenVitalsEntry,
  });

  int startEpochMs;

  int endEpochMs;

  double liters;

  String source;

  String id;

  String? clientRecordId;

  bool isOpenVitalsEntry;

  List<Object?> _toList() {
    return <Object?>[
      startEpochMs,
      endEpochMs,
      liters,
      source,
      id,
      clientRecordId,
      isOpenVitalsEntry,
    ];
  }

  Object encode() {
    return _toList();  }

  static HydrationEntryMsg decode(Object result) {
    result as List<Object?>;
    return HydrationEntryMsg(
      startEpochMs: result[0]! as int,
      endEpochMs: result[1]! as int,
      liters: result[2]! as double,
      source: result[3]! as String,
      id: result[4]! as String,
      clientRecordId: result[5] as String?,
      isOpenVitalsEntry: result[6]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HydrationEntryMsg || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(startEpochMs, other.startEpochMs) && _deepEquals(endEpochMs, other.endEpochMs) && _deepEquals(liters, other.liters) && _deepEquals(source, other.source) && _deepEquals(id, other.id) && _deepEquals(clientRecordId, other.clientRecordId) && _deepEquals(isOpenVitalsEntry, other.isOpenVitalsEntry);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'HydrationEntryMsg(startEpochMs: $startEpochMs, endEpochMs: $endEpochMs, liters: $liters, source: $source, id: $id, clientRecordId: $clientRecordId, isOpenVitalsEntry: $isOpenVitalsEntry)';
  }
}

/// One daily hydration total; [dateEpochMs] is local midnight of the day.
class DailyHydrationMsg {
  DailyHydrationMsg({
    required this.dateEpochMs,
    required this.liters,
  });

  int dateEpochMs;

  double liters;

  List<Object?> _toList() {
    return <Object?>[
      dateEpochMs,
      liters,
    ];
  }

  Object encode() {
    return _toList();  }

  static DailyHydrationMsg decode(Object result) {
    result as List<Object?>;
    return DailyHydrationMsg(
      dateEpochMs: result[0]! as int,
      liters: result[1]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DailyHydrationMsg || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(dateEpochMs, other.dateEpochMs) && _deepEquals(liters, other.liters);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'DailyHydrationMsg(dateEpochMs: $dateEpochMs, liters: $liters)';
  }
}

class HydrationWriteRequestMsg {
  HydrationWriteRequestMsg({
    required this.timeEpochMs,
    required this.volumeLiters,
    this.drinkId,
  });

  int timeEpochMs;

  double volumeLiters;

  String? drinkId;

  List<Object?> _toList() {
    return <Object?>[
      timeEpochMs,
      volumeLiters,
      drinkId,
    ];
  }

  Object encode() {
    return _toList();  }

  static HydrationWriteRequestMsg decode(Object result) {
    result as List<Object?>;
    return HydrationWriteRequestMsg(
      timeEpochMs: result[0]! as int,
      volumeLiters: result[1]! as double,
      drinkId: result[2] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HydrationWriteRequestMsg || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(timeEpochMs, other.timeEpochMs) && _deepEquals(volumeLiters, other.volumeLiters) && _deepEquals(drinkId, other.drinkId);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'HydrationWriteRequestMsg(timeEpochMs: $timeEpochMs, volumeLiters: $volumeLiters, drinkId: $drinkId)';
  }
}

class MindfulnessSessionMsg {
  MindfulnessSessionMsg({
    required this.id,
    this.title,
    required this.startEpochMs,
    required this.endEpochMs,
    required this.durationMs,
    required this.source,
    required this.isOpenVitalsEntry,
  });

  String id;

  String? title;

  int startEpochMs;

  int endEpochMs;

  int durationMs;

  String source;

  bool isOpenVitalsEntry;

  List<Object?> _toList() {
    return <Object?>[
      id,
      title,
      startEpochMs,
      endEpochMs,
      durationMs,
      source,
      isOpenVitalsEntry,
    ];
  }

  Object encode() {
    return _toList();  }

  static MindfulnessSessionMsg decode(Object result) {
    result as List<Object?>;
    return MindfulnessSessionMsg(
      id: result[0]! as String,
      title: result[1] as String?,
      startEpochMs: result[2]! as int,
      endEpochMs: result[3]! as int,
      durationMs: result[4]! as int,
      source: result[5]! as String,
      isOpenVitalsEntry: result[6]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MindfulnessSessionMsg || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) && _deepEquals(title, other.title) && _deepEquals(startEpochMs, other.startEpochMs) && _deepEquals(endEpochMs, other.endEpochMs) && _deepEquals(durationMs, other.durationMs) && _deepEquals(source, other.source) && _deepEquals(isOpenVitalsEntry, other.isOpenVitalsEntry);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'MindfulnessSessionMsg(id: $id, title: $title, startEpochMs: $startEpochMs, endEpochMs: $endEpochMs, durationMs: $durationMs, source: $source, isOpenVitalsEntry: $isOpenVitalsEntry)';
  }
}

class MindfulnessSessionWriteRequestMsg {
  MindfulnessSessionWriteRequestMsg({
    required this.title,
    required this.startEpochMs,
    required this.endEpochMs,
  });

  String title;

  int startEpochMs;

  int endEpochMs;

  List<Object?> _toList() {
    return <Object?>[
      title,
      startEpochMs,
      endEpochMs,
    ];
  }

  Object encode() {
    return _toList();  }

  static MindfulnessSessionWriteRequestMsg decode(Object result) {
    result as List<Object?>;
    return MindfulnessSessionWriteRequestMsg(
      title: result[0]! as String,
      startEpochMs: result[1]! as int,
      endEpochMs: result[2]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MindfulnessSessionWriteRequestMsg || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(title, other.title) && _deepEquals(startEpochMs, other.startEpochMs) && _deepEquals(endEpochMs, other.endEpochMs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'MindfulnessSessionWriteRequestMsg(title: $title, startEpochMs: $startEpochMs, endEpochMs: $endEpochMs)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is BodyMeasurementTypeMsg) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is HealthConnectAvailabilityDetail) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is WeightEntryMsg) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is HeightEntryMsg) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is BodyFatEntryMsg) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is BodyMassEntryMsg) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is BmrEntryMsg) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is BodyMeasurementEntryMsg) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    }    else if (value is BodyMeasurementWriteRequestMsg) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    }    else if (value is HydrationEntryMsg) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    }    else if (value is DailyHydrationMsg) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    }    else if (value is HydrationWriteRequestMsg) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    }    else if (value is MindfulnessSessionMsg) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    }    else if (value is MindfulnessSessionWriteRequestMsg) {
      buffer.putUint8(142);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : BodyMeasurementTypeMsg.values[value];
      case 130:
        return HealthConnectAvailabilityDetail.decode(readValue(buffer)!);
      case 131:
        return WeightEntryMsg.decode(readValue(buffer)!);
      case 132:
        return HeightEntryMsg.decode(readValue(buffer)!);
      case 133:
        return BodyFatEntryMsg.decode(readValue(buffer)!);
      case 134:
        return BodyMassEntryMsg.decode(readValue(buffer)!);
      case 135:
        return BmrEntryMsg.decode(readValue(buffer)!);
      case 136:
        return BodyMeasurementEntryMsg.decode(readValue(buffer)!);
      case 137:
        return BodyMeasurementWriteRequestMsg.decode(readValue(buffer)!);
      case 138:
        return HydrationEntryMsg.decode(readValue(buffer)!);
      case 139:
        return DailyHydrationMsg.decode(readValue(buffer)!);
      case 140:
        return HydrationWriteRequestMsg.decode(readValue(buffer)!);
      case 141:
        return MindfulnessSessionMsg.decode(readValue(buffer)!);
      case 142:
        return MindfulnessSessionWriteRequestMsg.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Host (Android/Kotlin) API surface backed by `HealthConnectClient`.
///
/// All record payloads are JSON strings; see the record JSON schema in
/// `lib/health_connect_native.dart`. Permission strings are Health Connect
/// permission identifiers (e.g. `android.permission.health.READ_STEPS`).
class HealthConnectHostApi {
  /// Constructor for [HealthConnectHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  HealthConnectHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Maps to `HealthConnectClient.getSdkStatus(context)`.
  ///
  /// Returns the raw SDK status int (e.g. `SDK_AVAILABLE`,
  /// `SDK_UNAVAILABLE`, `SDK_UNAVAILABLE_PROVIDER_UPDATE_REQUIRED`).
  Future<int> getSdkStatus() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.getSdkStatus$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as int;
  }

  /// Fuller availability picture than [getSdkStatus]: SDK status plus the
  /// work-profile and standalone-needs-Play-Store overrides, so Dart can resolve
  /// NOT_SUPPORTED / NEEDS_PLAY_STORE / NEEDS_PROVIDER_UPDATE / AVAILABLE.
  Future<HealthConnectAvailabilityDetail> availabilityDetail() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.availabilityDetail$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as HealthConnectAvailabilityDetail;
  }

  /// Mirrors the user's "pause Health Connect sync" toggle into the native
  /// sync-gate. While disabled, reads short-circuit to empty and writes throw.
  Future<void> setSyncEnabled(bool enabled) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.setSyncEnabled$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[enabled]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Returns the native sync-gate's current state.
  Future<bool> getSyncEnabled() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.getSyncEnabled$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Returns the subset of [permissions] currently granted.
  Future<List<String>> getGrantedPermissions(List<String> permissions) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.getGrantedPermissions$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[permissions]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<String>();
  }

  /// Launches the Health Connect permission contract via the Activity and
  /// resolves to whether every requested permission ended up granted.
  Future<bool> requestPermissions(List<String> permissions) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.requestPermissions$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[permissions]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Opens the Health Connect page for this app (app-specific permission
  /// management on Android 14+, falling back to Health Connect settings) so the
  /// user can manually grant permissions the runtime dialog reports as
  /// non-requestable (e.g. planned exercise, exercise routes, background/history
  /// access). Returns whether a page was launched.
  Future<bool> openHealthConnectSettings() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.openHealthConnectSettings$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Whether an optional Health Connect feature is available on this device,
  /// e.g. `"SKIN_TEMPERATURE"`, `"MINDFULNESS_SESSION"`, `"PLANNED_EXERCISE"`.
  Future<bool> isFeatureAvailable(String feature) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.isFeatureAvailable$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[feature]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Reads records of [recordType] in the [startEpochMs, endEpochMs] window,
  /// returning one JSON object (as a String) per record. [filterJson] is an
  /// optional JSON object carrying extra read constraints (data origins,
  /// paging, ascending/descending, page size, etc.).
  Future<List<String>> readRecordsJson(String recordType, int startEpochMs, int endEpochMs, String? filterJson) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.readRecordsJson$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[recordType, startEpochMs, endEpochMs, filterJson]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<String>();
  }

  /// Reads a single record of [recordType] by its Health Connect [recordId],
  /// or `null` if it does not exist.
  Future<String?> readRecordJson(String recordType, String recordId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.readRecordJson$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[recordType, recordId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as String?;
  }

  /// Runs an aggregation over [aggregateMetrics] in the given window, returning
  /// a metric-key -> value map (value is `null` when Health Connect has no data
  /// for that metric in the window).
  Future<Map<String, double?>> aggregate(List<String> aggregateMetrics, int startEpochMs, int endEpochMs) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.aggregate$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[aggregateMetrics, startEpochMs, endEpochMs]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as Map<Object?, Object?>).cast<String, double?>();
  }

  /// Aggregates [aggregateMetrics] grouped into buckets of [bucketType]
  /// (e.g. `"DAYS"`, `"WEEKS"`, `"MONTHS"`), returning one JSON object (as a
  /// String) per bucket with its time range and aggregated values.
  Future<List<String>> aggregateGroupByPeriodJson(List<String> aggregateMetrics, int startEpochMs, int endEpochMs, String bucketType) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.aggregateGroupByPeriodJson$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[aggregateMetrics, startEpochMs, endEpochMs, bucketType]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<String>();
  }

  /// Inserts the given records (each a JSON object String matching the canonical
  /// schema) and returns the inserted Health Connect record ids in order.
  Future<List<String>> insertRecordsJson(List<String> recordsJson) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.insertRecordsJson$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[recordsJson]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<String>();
  }

  /// Deletes records of [recordType] by their app-assigned client record ids.
  Future<void> deleteRecordsByClientIds(String recordType, List<String> clientRecordIds) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.deleteRecordsByClientIds$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[recordType, clientRecordIds]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Deletes records of [recordType] by their Health Connect record ids.
  Future<void> deleteRecordsByIds(String recordType, List<String> recordIds) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.deleteRecordsByIds$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[recordType, recordIds]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Import dedup helper: of the supplied [clientRecordIds], returns the subset
  /// that ALREADY exist in Health Connect for [recordType].
  Future<List<String>> filterExistingClientIds(String recordType, List<String> clientRecordIds) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.filterExistingClientIds$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[recordType, clientRecordIds]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<String>();
  }

  Future<List<WeightEntryMsg>> readWeightEntries(int startEpochMs, int endEpochMs) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.readWeightEntries$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[startEpochMs, endEpochMs]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<WeightEntryMsg>();
  }

  Future<WeightEntryMsg?> readLatestWeight() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.readLatestWeight$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as WeightEntryMsg?;
  }

  Future<List<HeightEntryMsg>> readHeightEntries(int startEpochMs, int endEpochMs) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.readHeightEntries$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[startEpochMs, endEpochMs]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<HeightEntryMsg>();
  }

  Future<HeightEntryMsg?> readLatestHeightEntry() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.readLatestHeightEntry$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as HeightEntryMsg?;
  }

  Future<List<BodyFatEntryMsg>> readBodyFatEntries(int startEpochMs, int endEpochMs) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.readBodyFatEntries$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[startEpochMs, endEpochMs]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<BodyFatEntryMsg>();
  }

  Future<BodyFatEntryMsg?> readLatestBodyFat() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.readLatestBodyFat$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as BodyFatEntryMsg?;
  }

  Future<List<BodyMassEntryMsg>> readLeanBodyMassEntries(int startEpochMs, int endEpochMs) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.readLeanBodyMassEntries$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[startEpochMs, endEpochMs]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<BodyMassEntryMsg>();
  }

  Future<BodyMassEntryMsg?> readLatestLeanBodyMass() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.readLatestLeanBodyMass$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as BodyMassEntryMsg?;
  }

  Future<List<BmrEntryMsg>> readBmrEntries(int startEpochMs, int endEpochMs) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.readBmrEntries$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[startEpochMs, endEpochMs]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<BmrEntryMsg>();
  }

  Future<BmrEntryMsg?> readLatestBmr() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.readLatestBmr$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as BmrEntryMsg?;
  }

  Future<List<BodyMassEntryMsg>> readBoneMassEntries(int startEpochMs, int endEpochMs) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.readBoneMassEntries$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[startEpochMs, endEpochMs]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<BodyMassEntryMsg>();
  }

  Future<BodyMassEntryMsg?> readLatestBoneMass() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.readLatestBoneMass$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as BodyMassEntryMsg?;
  }

  Future<List<BodyMassEntryMsg>> readBodyWaterMassEntries(int startEpochMs, int endEpochMs) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.readBodyWaterMassEntries$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[startEpochMs, endEpochMs]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<BodyMassEntryMsg>();
  }

  Future<BodyMassEntryMsg?> readLatestBodyWaterMass() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.readLatestBodyWaterMass$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as BodyMassEntryMsg?;
  }

  Future<String> writeBodyMeasurementEntry(BodyMeasurementWriteRequestMsg request) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.writeBodyMeasurementEntry$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as String;
  }

  Future<BodyMeasurementEntryMsg?> readBodyMeasurementEntry(BodyMeasurementTypeMsg type, String id) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.readBodyMeasurementEntry$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[type, id]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as BodyMeasurementEntryMsg?;
  }

  Future<void> updateBodyMeasurementEntry(String id, BodyMeasurementWriteRequestMsg request) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.updateBodyMeasurementEntry$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[id, request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> deleteBodyMeasurementEntry(BodyMeasurementTypeMsg type, String id) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.deleteBodyMeasurementEntry$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[type, id]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<double?> readHydrationLiters(int startEpochMs, int endEpochMs) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.readHydrationLiters$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[startEpochMs, endEpochMs]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as double?;
  }

  Future<List<DailyHydrationMsg>> readDailyHydration(int startEpochMs, int endEpochMs) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.readDailyHydration$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[startEpochMs, endEpochMs]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<DailyHydrationMsg>();
  }

  Future<List<HydrationEntryMsg>> readHydrationEntries(int startEpochMs, int endEpochMs) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.readHydrationEntries$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[startEpochMs, endEpochMs]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<HydrationEntryMsg>();
  }

  Future<HydrationEntryMsg?> readHydrationEntry(String id) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.readHydrationEntry$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[id]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as HydrationEntryMsg?;
  }

  Future<String> writeHydrationEntry(HydrationWriteRequestMsg request) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.writeHydrationEntry$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as String;
  }

  Future<void> updateHydrationEntry(String id, HydrationWriteRequestMsg request) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.updateHydrationEntry$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[id, request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<String?> deleteHydrationEntry(String id) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.deleteHydrationEntry$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[id]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as String?;
  }

  Future<List<MindfulnessSessionMsg>> readMindfulnessSessions(int startEpochMs, int endEpochMs) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.readMindfulnessSessions$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[startEpochMs, endEpochMs]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<MindfulnessSessionMsg>();
  }

  Future<MindfulnessSessionMsg?> readMindfulnessSession(String id) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.readMindfulnessSession$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[id]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as MindfulnessSessionMsg?;
  }

  Future<int> readMindfulnessMinutes(int startEpochMs, int endEpochMs) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.readMindfulnessMinutes$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[startEpochMs, endEpochMs]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as int;
  }

  Future<String> writeMindfulnessSessionEntry(MindfulnessSessionWriteRequestMsg request) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.writeMindfulnessSessionEntry$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as String;
  }

  Future<void> updateMindfulnessSessionEntry(String id, MindfulnessSessionWriteRequestMsg request) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.updateMindfulnessSessionEntry$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[id, request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> deleteMindfulnessSessionEntry(String id) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.deleteMindfulnessSessionEntry$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[id]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}
