package tech.mmarca.openvitals.health_connect_native

import androidx.health.connect.client.records.ActiveCaloriesBurnedRecord
import androidx.health.connect.client.records.CyclingPedalingCadenceRecord
import androidx.health.connect.client.records.DistanceRecord
import androidx.health.connect.client.records.ElevationGainedRecord
import androidx.health.connect.client.records.ExerciseSessionRecord
import androidx.health.connect.client.records.HeartRateRecord
import androidx.health.connect.client.records.PowerRecord
import androidx.health.connect.client.records.Record
import androidx.health.connect.client.records.SleepSessionRecord
import androidx.health.connect.client.records.SpeedRecord
import androidx.health.connect.client.records.StepsCadenceRecord
import androidx.health.connect.client.records.StepsRecord
import androidx.health.connect.client.records.TotalCaloriesBurnedRecord
import androidx.health.connect.client.records.metadata.DataOrigin
import androidx.health.connect.client.records.metadata.Device
import androidx.health.connect.client.records.metadata.Metadata
import androidx.health.connect.client.testing.populatedWithTestValues
import androidx.health.connect.client.units.Energy
import androidx.health.connect.client.units.Length
import androidx.health.connect.client.units.Power
import androidx.health.connect.client.units.Velocity
import com.google.gson.Gson
import com.google.gson.JsonArray
import com.google.gson.JsonObject
import java.time.Instant
import java.time.ZoneOffset

/**
 * The shared fixture, turned back into real Health Connect [Record]s.
 *
 * `test/fixtures/health_connect/golden.json` is generated by
 * `tool/health_fixture/build.dart` from a real Health Connect export, and it is the
 * SAME file the Dart tier reads — Gradle puts it on this module's test classpath
 * rather than copying it, because two copies of a fixture drift, and a drifted
 * fixture is a suite that is green about the wrong data.
 *
 * What matters here is the PROVENANCE. Every record is rebuilt with its real
 * `dataOrigin` (so multi-writer dedup means something), its real `recordingMethod`
 * (so the manual-entry count means something), its real `lastModifiedTime` (so the
 * dedup tie-break means something) and its real boundaries (so the 17.48-hour
 * record still swallows its workout). Those are exactly the fields the Flutter port
 * kept losing, and a fixture that reconstructed records without them would let the
 * same bug straight back in.
 */
object HcFixture {

  private val root: JsonObject by lazy {
    val stream = HcFixture::class.java.classLoader!!.getResourceAsStream("golden.json")
      ?: error(
        "golden.json is not on the test classpath. It is generated by " +
          "`dart run tool/health_fixture/build.dart` and committed at the repo root; " +
          "build.gradle adds it as a test resource.",
      )
    Gson().fromJson(stream.reader(), JsonObject::class.java)
  }

  /** Every record in the fixture, ready to insert into a HealthConnectClient. */
  fun allRecords(): List<Record> =
    heartRate() + exercise() + sleep() + speed() + stepsCadence() + power() +
      cyclingCadence() + steps() + distance() + activeCalories() + totalCalories() +
      elevationGained()

  // ── the swallowing record, and the workout it swallows ──────────────────────

  /** The longest heart-rate record — the one that hides a workout inside itself. */
  fun swallowingHeartRateRecord(): HeartRateRecord =
    heartRate().maxByOrNull { it.endTime.toEpochMilli() - it.startTime.toEpochMilli() }!!

  /** The exercise session that sits inside it. */
  fun swallowedWorkout(): ExerciseSessionRecord {
    val hr = swallowingHeartRateRecord()
    return exercise().first {
      !it.startTime.isBefore(hr.startTime) && !it.endTime.isAfter(hr.endTime)
    }
  }

  /** The session with a GPS route — the long outdoor one. */
  fun routeWorkout(): ExerciseSessionRecord {
    val withRoute = array("exercise")
      .map { it.asJsonObject }
      .maxByOrNull { it["route"].asJsonArray.size() }!!
    return exercise().first { it.metadata.id == withRoute["id"].asString }
  }

  // ── records ─────────────────────────────────────────────────────────────────

  fun heartRate(): List<HeartRateRecord> = array("heartRate").map { e ->
    val o = e.asJsonObject
    val times = sampleTimes(o)
    val bpm = o["bpm"].asJsonArray
    HeartRateRecord(
      startTime = instant(o, "start"),
      startZoneOffset = zone(o, "startZoneOffsetSeconds"),
      endTime = instant(o, "end"),
      endZoneOffset = zone(o, "endZoneOffsetSeconds"),
      samples = times.mapIndexed { i, t ->
        HeartRateRecord.Sample(time = t, beatsPerMinute = bpm[i].asLong)
      },
      metadata = metadata(o),
    )
  }

  fun exercise(): List<ExerciseSessionRecord> = array("exercise").map { e ->
    val o = e.asJsonObject
    ExerciseSessionRecord(
      startTime = instant(o, "start"),
      startZoneOffset = zone(o, "startZoneOffsetSeconds"),
      endTime = instant(o, "end"),
      endZoneOffset = zone(o, "endZoneOffsetSeconds"),
      exerciseType = o["exerciseType"].asInt,
      title = o["title"].takeIf { !it.isJsonNull }?.asString,
      notes = o["notes"].takeIf { !it.isJsonNull }?.asString,
      metadata = metadata(o),
    )
  }

  fun sleep(): List<SleepSessionRecord> = array("sleep").map { e ->
    val o = e.asJsonObject
    SleepSessionRecord(
      startTime = instant(o, "start"),
      startZoneOffset = zone(o, "startZoneOffsetSeconds"),
      endTime = instant(o, "end"),
      endZoneOffset = zone(o, "endZoneOffsetSeconds"),
      title = o["title"].takeIf { !it.isJsonNull }?.asString,
      notes = o["notes"].takeIf { !it.isJsonNull }?.asString,
      stages = o["stages"].asJsonArray.map { s ->
        val st = s.asJsonObject
        SleepSessionRecord.Stage(
          startTime = Instant.ofEpochMilli(st["start"].asLong),
          endTime = Instant.ofEpochMilli(st["end"].asLong),
          stage = st["type"].asInt,
        )
      },
      metadata = metadata(o),
    )
  }

  fun speed(): List<SpeedRecord> = array("speed").map { e ->
    val o = e.asJsonObject
    val times = sampleTimes(o)
    val v = o["v"].asJsonArray
    SpeedRecord(
      startTime = instant(o, "start"),
      startZoneOffset = zone(o, "startZoneOffsetSeconds"),
      endTime = instant(o, "end"),
      endZoneOffset = zone(o, "endZoneOffsetSeconds"),
      samples = times.mapIndexed { i, t ->
        SpeedRecord.Sample(time = t, speed = Velocity.metersPerSecond(v[i].asDouble))
      },
      metadata = metadata(o),
    )
  }

  fun stepsCadence(): List<StepsCadenceRecord> = array("stepsCadence").map { e ->
    val o = e.asJsonObject
    val times = sampleTimes(o)
    val v = o["v"].asJsonArray
    StepsCadenceRecord(
      startTime = instant(o, "start"),
      startZoneOffset = zone(o, "startZoneOffsetSeconds"),
      endTime = instant(o, "end"),
      endZoneOffset = zone(o, "endZoneOffsetSeconds"),
      samples = times.mapIndexed { i, t ->
        StepsCadenceRecord.Sample(time = t, rate = v[i].asDouble)
      },
      metadata = metadata(o),
    )
  }

  fun power(): List<PowerRecord> = array("power").map { e ->
    val o = e.asJsonObject
    val times = sampleTimes(o)
    val v = o["v"].asJsonArray
    PowerRecord(
      startTime = instant(o, "start"),
      startZoneOffset = zone(o, "startZoneOffsetSeconds"),
      endTime = instant(o, "end"),
      endZoneOffset = zone(o, "endZoneOffsetSeconds"),
      samples = times.mapIndexed { i, t ->
        PowerRecord.Sample(time = t, power = Power.watts(v[i].asDouble))
      },
      metadata = metadata(o),
    )
  }

  fun cyclingCadence(): List<CyclingPedalingCadenceRecord> =
    array("cyclingCadence").map { e ->
      val o = e.asJsonObject
      val times = sampleTimes(o)
      val v = o["v"].asJsonArray
      CyclingPedalingCadenceRecord(
        startTime = instant(o, "start"),
        startZoneOffset = zone(o, "startZoneOffsetSeconds"),
        endTime = instant(o, "end"),
        endZoneOffset = zone(o, "endZoneOffsetSeconds"),
        samples = times.mapIndexed { i, t ->
          CyclingPedalingCadenceRecord.Sample(time = t, revolutionsPerMinute = v[i].asDouble)
        },
        metadata = metadata(o),
      )
    }

  // The sibling records: what a watch writes BESIDE a session instead of in it.
  fun steps(): List<StepsRecord> = array("steps").map { e ->
    val o = e.asJsonObject
    StepsRecord(
      startTime = instant(o, "start"),
      startZoneOffset = zone(o, "startZoneOffsetSeconds"),
      endTime = instant(o, "end"),
      endZoneOffset = zone(o, "endZoneOffsetSeconds"),
      count = o["count"].asLong.coerceAtLeast(1L),
      metadata = metadata(o),
    )
  }

  fun distance(): List<DistanceRecord> = array("distance").map { e ->
    val o = e.asJsonObject
    DistanceRecord(
      startTime = instant(o, "start"),
      startZoneOffset = zone(o, "startZoneOffsetSeconds"),
      endTime = instant(o, "end"),
      endZoneOffset = zone(o, "endZoneOffsetSeconds"),
      distance = Length.meters(o["v"].asDouble),
      metadata = metadata(o),
    )
  }

  fun activeCalories(): List<ActiveCaloriesBurnedRecord> =
    array("activeCalories").map { e ->
      val o = e.asJsonObject
      ActiveCaloriesBurnedRecord(
        startTime = instant(o, "start"),
        startZoneOffset = zone(o, "startZoneOffsetSeconds"),
        endTime = instant(o, "end"),
        endZoneOffset = zone(o, "endZoneOffsetSeconds"),
        energy = Energy.joules(o["v"].asDouble),
        metadata = metadata(o),
      )
    }

  fun totalCalories(): List<TotalCaloriesBurnedRecord> =
    array("totalCalories").map { e ->
      val o = e.asJsonObject
      TotalCaloriesBurnedRecord(
        startTime = instant(o, "start"),
        startZoneOffset = zone(o, "startZoneOffsetSeconds"),
        endTime = instant(o, "end"),
        endZoneOffset = zone(o, "endZoneOffsetSeconds"),
        energy = Energy.joules(o["v"].asDouble),
        metadata = metadata(o),
      )
    }

  fun elevationGained(): List<ElevationGainedRecord> =
    array("elevationGained").map { e ->
      val o = e.asJsonObject
      ElevationGainedRecord(
        startTime = instant(o, "start"),
        startZoneOffset = zone(o, "startZoneOffsetSeconds"),
        endTime = instant(o, "end"),
        endZoneOffset = zone(o, "endZoneOffsetSeconds"),
        elevation = Length.meters(o["v"].asDouble),
        metadata = metadata(o),
      )
    }

  // ── plumbing ────────────────────────────────────────────────────────────────

  private fun array(key: String): JsonArray = root[key].asJsonArray

  private fun instant(o: JsonObject, key: String): Instant =
    Instant.ofEpochMilli(o[key].asLong)

  private fun zone(o: JsonObject, key: String): ZoneOffset? =
    o[key]?.takeIf { !it.isJsonNull }?.let { ZoneOffset.ofTotalSeconds(it.asInt) }

  /** Delta-decoded: `t0` plus the running sum of `dt`. */
  private fun sampleTimes(o: JsonObject): List<Instant> {
    var t = o["t0"].asLong
    val out = mutableListOf(Instant.ofEpochMilli(t))
    o["dt"].asJsonArray.forEach {
      t += it.asLong
      out.add(Instant.ofEpochMilli(t))
    }
    return out
  }

  /**
   * The provenance, rebuilt in full.
   *
   * This is the part that matters. `dataOrigin`, `recordingMethod` and
   * `lastModifiedTime` are precisely the fields the Pigeon messages dropped — and a
   * fixture loader that quietly defaulted them would let that bug straight back in
   * while every test stayed green.
   */
  private fun metadata(o: JsonObject): Metadata {
    val clientId = o["clientRecordId"]?.takeIf { !it.isJsonNull }?.asString
    val clientVersion =
      o["clientRecordVersion"]?.takeIf { !it.isJsonNull }?.asLong ?: 0L
    val device = Device(type = Device.TYPE_WATCH)

    // Metadata's full constructor is INTERNAL to the library — the recording method
    // is only settable by choosing the right factory. Which is a good design: it
    // makes "how was this recorded" a decision rather than an integer someone
    // forgot. So the fixture's recordingMethod picks the factory, and the record
    // that says MANUAL_ENTRY really is a manual entry as far as Health Connect is
    // concerned — which is what the activities screen's manual-entry count reads.
    // The clientRecordId overloads take it NON-null; a record without one uses the
    // shorter factory. Which is real: a watch that writes its own idempotency key
    // and a phone that does not are different records, and the app's
    // dedup-by-clientRecordId only fires for the first kind.
    val base = when (o["recordingMethod"]?.takeIf { !it.isJsonNull }?.asInt) {
      Metadata.RECORDING_METHOD_ACTIVELY_RECORDED ->
        if (clientId != null) Metadata.activelyRecorded(device, clientId, clientVersion)
        else Metadata.activelyRecorded(device)
      Metadata.RECORDING_METHOD_AUTOMATICALLY_RECORDED ->
        if (clientId != null) Metadata.autoRecorded(device, clientId, clientVersion)
        else Metadata.autoRecorded(device)
      Metadata.RECORDING_METHOD_MANUAL_ENTRY ->
        if (clientId != null) Metadata.manualEntry(clientId, clientVersion, device)
        else Metadata.manualEntry(device)
      else ->
        if (clientId != null) Metadata.unknownRecordingMethod(clientId, clientVersion, device)
        else Metadata.unknownRecordingMethod(device)
    }

    // The rest of the provenance. `dataOrigin` and `lastModifiedTime` are the two
    // fields the Pigeon messages dropped, and they are also the two Health Connect
    // will not let an app set on a real device — which is precisely why
    // connect-testing exposes this and why multi-writer dedup and the
    // lastModifiedTime tie-break are testable HERE and nowhere else.
    return base.populatedWithTestValues(
      id = o["id"].asString,
      dataOrigin = DataOrigin(o["writer"].asString),
      lastModifiedTime = o["lastModified"]?.takeIf { !it.isJsonNull }
        ?.let { Instant.ofEpochMilli(it.asLong) } ?: Instant.EPOCH,
    )
  }
}
