package tech.mmarca.openvitals.features.activity

import androidx.health.connect.client.records.ExerciseSegment
import androidx.health.connect.client.records.ExerciseSessionRecord
import androidx.health.connect.client.records.metadata.Device
import androidx.health.connect.client.records.metadata.Metadata

internal fun exerciseTypeLabel(type: Int): String = when (type) {
    ExerciseSessionRecord.EXERCISE_TYPE_BADMINTON -> "Badminton"
    ExerciseSessionRecord.EXERCISE_TYPE_BASEBALL -> "Baseball"
    ExerciseSessionRecord.EXERCISE_TYPE_BASKETBALL -> "Basketball"
    ExerciseSessionRecord.EXERCISE_TYPE_BIKING -> "Biking"
    ExerciseSessionRecord.EXERCISE_TYPE_BIKING_STATIONARY -> "Biking (stationary)"
    ExerciseSessionRecord.EXERCISE_TYPE_BOOT_CAMP -> "Boot camp"
    ExerciseSessionRecord.EXERCISE_TYPE_BOXING -> "Boxing"
    ExerciseSessionRecord.EXERCISE_TYPE_CALISTHENICS -> "Calisthenics"
    ExerciseSessionRecord.EXERCISE_TYPE_CRICKET -> "Cricket"
    ExerciseSessionRecord.EXERCISE_TYPE_DANCING -> "Dancing"
    ExerciseSessionRecord.EXERCISE_TYPE_ELLIPTICAL -> "Elliptical"
    ExerciseSessionRecord.EXERCISE_TYPE_EXERCISE_CLASS -> "Exercise class"
    ExerciseSessionRecord.EXERCISE_TYPE_FENCING -> "Fencing"
    ExerciseSessionRecord.EXERCISE_TYPE_FOOTBALL_AMERICAN -> "Football (American)"
    ExerciseSessionRecord.EXERCISE_TYPE_FOOTBALL_AUSTRALIAN -> "Football (Australian)"
    ExerciseSessionRecord.EXERCISE_TYPE_FRISBEE_DISC -> "Frisbee disc"
    ExerciseSessionRecord.EXERCISE_TYPE_GOLF -> "Golf"
    ExerciseSessionRecord.EXERCISE_TYPE_GUIDED_BREATHING -> "Guided breathing"
    ExerciseSessionRecord.EXERCISE_TYPE_GYMNASTICS -> "Gymnastics"
    ExerciseSessionRecord.EXERCISE_TYPE_HANDBALL -> "Handball"
    ExerciseSessionRecord.EXERCISE_TYPE_HIGH_INTENSITY_INTERVAL_TRAINING -> "High intensity interval training"
    ExerciseSessionRecord.EXERCISE_TYPE_HIKING -> "Hiking"
    ExerciseSessionRecord.EXERCISE_TYPE_ICE_HOCKEY -> "Ice hockey"
    ExerciseSessionRecord.EXERCISE_TYPE_ICE_SKATING -> "Ice skating"
    ExerciseSessionRecord.EXERCISE_TYPE_MARTIAL_ARTS -> "Martial arts"
    ExerciseSessionRecord.EXERCISE_TYPE_PADDLING -> "Paddling"
    ExerciseSessionRecord.EXERCISE_TYPE_PARAGLIDING -> "Paragliding"
    ExerciseSessionRecord.EXERCISE_TYPE_PILATES -> "Pilates"
    ExerciseSessionRecord.EXERCISE_TYPE_RACQUETBALL -> "Racquetball"
    ExerciseSessionRecord.EXERCISE_TYPE_ROCK_CLIMBING -> "Rock climbing"
    ExerciseSessionRecord.EXERCISE_TYPE_ROLLER_HOCKEY -> "Roller hockey"
    ExerciseSessionRecord.EXERCISE_TYPE_ROWING -> "Rowing"
    ExerciseSessionRecord.EXERCISE_TYPE_ROWING_MACHINE -> "Rowing (machine)"
    ExerciseSessionRecord.EXERCISE_TYPE_RUGBY -> "Rugby"
    ExerciseSessionRecord.EXERCISE_TYPE_RUNNING -> "Running"
    ExerciseSessionRecord.EXERCISE_TYPE_RUNNING_TREADMILL -> "Running (treadmill)"
    ExerciseSessionRecord.EXERCISE_TYPE_SAILING -> "Sailing"
    ExerciseSessionRecord.EXERCISE_TYPE_SCUBA_DIVING -> "Scuba diving"
    ExerciseSessionRecord.EXERCISE_TYPE_SKATING -> "Skating"
    ExerciseSessionRecord.EXERCISE_TYPE_SKIING -> "Skiing"
    ExerciseSessionRecord.EXERCISE_TYPE_SNOWBOARDING -> "Snowboarding"
    ExerciseSessionRecord.EXERCISE_TYPE_SNOWSHOEING -> "Snowshoeing"
    ExerciseSessionRecord.EXERCISE_TYPE_SOCCER -> "Soccer"
    ExerciseSessionRecord.EXERCISE_TYPE_SOFTBALL -> "Softball"
    ExerciseSessionRecord.EXERCISE_TYPE_SQUASH -> "Squash"
    ExerciseSessionRecord.EXERCISE_TYPE_STAIR_CLIMBING -> "Stair climbing"
    ExerciseSessionRecord.EXERCISE_TYPE_STAIR_CLIMBING_MACHINE -> "Stair climbing (machine)"
    ExerciseSessionRecord.EXERCISE_TYPE_STRENGTH_TRAINING -> "Strength training"
    ExerciseSessionRecord.EXERCISE_TYPE_STRETCHING -> "Stretching"
    ExerciseSessionRecord.EXERCISE_TYPE_SURFING -> "Surfing"
    ExerciseSessionRecord.EXERCISE_TYPE_SWIMMING_OPEN_WATER -> "Swimming (open water)"
    ExerciseSessionRecord.EXERCISE_TYPE_SWIMMING_POOL -> "Swimming (pool)"
    ExerciseSessionRecord.EXERCISE_TYPE_TABLE_TENNIS -> "Table tennis"
    ExerciseSessionRecord.EXERCISE_TYPE_TENNIS -> "Tennis"
    ExerciseSessionRecord.EXERCISE_TYPE_VOLLEYBALL -> "Volleyball"
    ExerciseSessionRecord.EXERCISE_TYPE_WALKING -> "Walking"
    ExerciseSessionRecord.EXERCISE_TYPE_WATER_POLO -> "Water polo"
    ExerciseSessionRecord.EXERCISE_TYPE_WEIGHTLIFTING -> "Weightlifting"
    ExerciseSessionRecord.EXERCISE_TYPE_WHEELCHAIR -> "Wheelchair"
    ExerciseSessionRecord.EXERCISE_TYPE_YOGA -> "Yoga"
    else -> "Exercise"
}

internal fun exerciseSegmentLabel(type: Int): String = when (type) {
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_ARM_CURL -> "Arm curl"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_BACK_EXTENSION -> "Back extension"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_BALL_SLAM -> "Ball slam"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_BARBELL_SHOULDER_PRESS -> "Barbell shoulder press"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_BENCH_PRESS -> "Bench press"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_BENCH_SIT_UP -> "Bench sit up"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_BIKING -> "Biking"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_BIKING_STATIONARY -> "Biking (stationary)"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_BURPEE -> "Burpee"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_CRUNCH -> "Crunch"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_DEADLIFT -> "Deadlift"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_DOUBLE_ARM_TRICEPS_EXTENSION -> "Double arm triceps extension"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_DUMBBELL_CURL_LEFT_ARM -> "Dumbbell curl (left arm)"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_DUMBBELL_CURL_RIGHT_ARM -> "Dumbbell curl (right arm)"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_DUMBBELL_FRONT_RAISE -> "Dumbbell front raise"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_DUMBBELL_LATERAL_RAISE -> "Dumbbell lateral raise"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_DUMBBELL_ROW -> "Dumbbell row"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_DUMBBELL_TRICEPS_EXTENSION_LEFT_ARM -> "Dumbbell triceps extension (left arm)"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_DUMBBELL_TRICEPS_EXTENSION_RIGHT_ARM -> "Dumbbell triceps extension (right arm)"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_DUMBBELL_TRICEPS_EXTENSION_TWO_ARM -> "Dumbbell triceps extension (two arm)"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_ELLIPTICAL -> "Elliptical"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_FORWARD_TWIST -> "Forward twist"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_FRONT_RAISE -> "Front raise"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_HIGH_INTENSITY_INTERVAL_TRAINING -> "High intensity interval training"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_HIP_THRUST -> "Hip thrust"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_HULA_HOOP -> "Hula hoop"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_JUMPING_JACK -> "Jumping jack"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_JUMP_ROPE -> "Jump rope"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_KETTLEBELL_SWING -> "Kettlebell swing"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_LATERAL_RAISE -> "Lateral raise"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_LAT_PULL_DOWN -> "Lat pull-down"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_LEG_CURL -> "Leg curl"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_LEG_EXTENSION -> "Leg extension"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_LEG_PRESS -> "Leg press"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_LEG_RAISE -> "Leg raise"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_LUNGE -> "Lunge"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_MOUNTAIN_CLIMBER -> "Mountain climber"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_OTHER_WORKOUT -> "Other workout"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_PAUSE -> "Pause"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_PILATES -> "Pilates"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_PLANK -> "Plank"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_PULL_UP -> "Pull-up"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_PUNCH -> "Punch"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_REST -> "Rest"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_ROWING_MACHINE -> "Rowing machine"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_RUNNING -> "Running"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_RUNNING_TREADMILL -> "Running (treadmill)"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_SHOULDER_PRESS -> "Shoulder press"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_SINGLE_ARM_TRICEPS_EXTENSION -> "Single arm triceps extension"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_SIT_UP -> "Sit-up"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_SQUAT -> "Squat"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_STAIR_CLIMBING -> "Stair climbing"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_STAIR_CLIMBING_MACHINE -> "Stair climbing (machine)"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_STRETCHING -> "Stretching"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_SWIMMING_BACKSTROKE -> "Swimming backstroke"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_SWIMMING_BREASTSTROKE -> "Swimming breaststroke"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_SWIMMING_BUTTERFLY -> "Swimming butterfly"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_SWIMMING_FREESTYLE -> "Swimming freestyle"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_SWIMMING_MIXED -> "Swimming mixed"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_SWIMMING_OPEN_WATER -> "Swimming open water"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_SWIMMING_OTHER -> "Swimming other"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_SWIMMING_POOL -> "Swimming pool"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_UPPER_TWIST -> "Upper twist"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_WALKING -> "Walking"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_WEIGHTLIFTING -> "Weightlifting"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_WHEELCHAIR -> "Wheelchair"
    ExerciseSegment.EXERCISE_SEGMENT_TYPE_YOGA -> "Yoga"
    else -> "Unknown"
}

internal fun recordingMethodLabel(method: Int?): String = when (method) {
    Metadata.RECORDING_METHOD_ACTIVELY_RECORDED -> "Actively recorded"
    Metadata.RECORDING_METHOD_AUTOMATICALLY_RECORDED -> "Automatically recorded"
    Metadata.RECORDING_METHOD_MANUAL_ENTRY -> "Manual entry"
    Metadata.RECORDING_METHOD_UNKNOWN -> "Unknown"
    else -> "Not available"
}

internal fun deviceTypeLabel(type: Int?): String = when (type) {
    Device.TYPE_WATCH -> "Watch"
    Device.TYPE_PHONE -> "Phone"
    Device.TYPE_SCALE -> "Scale"
    Device.TYPE_RING -> "Ring"
    Device.TYPE_HEAD_MOUNTED -> "Head-mounted"
    Device.TYPE_FITNESS_BAND -> "Fitness band"
    Device.TYPE_CHEST_STRAP -> "Chest strap"
    Device.TYPE_SMART_DISPLAY -> "Smart display"
    Device.TYPE_UNKNOWN -> "Unknown"
    else -> "Not available"
}
