package tech.mmarca.openvitals.domain.insights

import java.text.Normalizer
import java.util.Locale
import tech.mmarca.openvitals.domain.model.CaffeineCatalogItem
import tech.mmarca.openvitals.domain.model.CaffeineCatalogMatch
import tech.mmarca.openvitals.domain.model.CaffeineCatalogMatchConfidence
import tech.mmarca.openvitals.domain.model.CaffeineEntry
import tech.mmarca.openvitals.domain.model.CaffeineSourceCategory
import tech.mmarca.openvitals.domain.model.CustomHydrationDrink

/**
 * Static matching metadata derived from CaffeineHealth GPL-3.0 consumable_items.json.
 * OpenVitals uses it as seed/matching metadata for beverages; Health Connect remains
 * the source of truth for logged nutrition records.
 */
object CaffeineHealthDrinkCatalog {
    private const val BeveragePresetIdPrefix = "caffeinehealth-"
    private val CombiningMarks = Regex("\\p{Mn}+")
    private val NonAlphaNumeric = Regex("[^a-z0-9]+")

    val items: List<CaffeineCatalogItem> = listOf(
        CaffeineCatalogItem(
            id = "drip-coffee",
            name = "Drip coffee",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 95.0,
            defaultServingMilliliters = 240.0,
            aliases = listOf("coffee", "brewed coffee", "filter coffee", "regular coffee"),
        ),
        CaffeineCatalogItem(
            id = "espresso",
            name = "Espresso",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 77.0,
            defaultServingMilliliters = 44.3,
            aliases = listOf("single espresso", "double espresso", "espresso shot"),
        ),
        CaffeineCatalogItem(
            id = "instant-coffee",
            name = "Instant Coffee",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 57.0,
            defaultServingMilliliters = 240.0,
        ),
        CaffeineCatalogItem(
            id = "tea-black",
            name = "Tea (Black)",
            category = CaffeineSourceCategory.TEA,
            typicalCaffeineMg = 48.0,
            defaultServingMilliliters = 240.0,
            aliases = listOf("black tea"),
        ),
        CaffeineCatalogItem(
            id = "costa-espresso",
            name = "Costa Espresso",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 100.0,
            defaultServingMilliliters = 30.0,
        ),
        CaffeineCatalogItem(
            id = "americano",
            name = "Americano",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 77.0,
            defaultServingMilliliters = 30.0,
            aliases = listOf("cafe americano", "caffe americano"),
        ),
        CaffeineCatalogItem(
            id = "monster-energy-ultra",
            name = "Monster Energy Ultra",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 150.0,
            defaultServingMilliliters = 473.0,
            aliases = listOf("monster ultra"),
        ),
        CaffeineCatalogItem(
            id = "decaf-instant-coffee",
            name = "Decaf instant coffee",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 2.4,
            defaultServingMilliliters = 240.0,
        ),
        CaffeineCatalogItem(
            id = "coca-cola-zero",
            name = "Coca-Cola Zero",
            category = CaffeineSourceCategory.SODA,
            typicalCaffeineMg = 32.0,
            defaultServingMilliliters = 333.0,
            aliases = listOf("coke zero"),
        ),
        CaffeineCatalogItem(
            id = "cappuccino",
            name = "Cappuccino",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 77.0,
            defaultServingMilliliters = 200.0,
            aliases = listOf("capuccino"),
        ),
        CaffeineCatalogItem(
            id = "pepsi",
            name = "Pepsi",
            category = CaffeineSourceCategory.SODA,
            typicalCaffeineMg = 38.0205,
            defaultServingMilliliters = 355.0,
        ),
        CaffeineCatalogItem(
            id = "nescafe-classic",
            name = "Nescaf\u00e9 Classic",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 75.0,
            defaultServingMilliliters = 240.0,
        ),
        CaffeineCatalogItem(
            id = "red-bull",
            name = "Red Bull",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 80.0,
            defaultServingMilliliters = 250.0,
            aliases = listOf("redbull", "red bull energy"),
        ),
        CaffeineCatalogItem(
            id = "caff-latte",
            name = "Caff\u00e8 Latte",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 77.0,
            defaultServingMilliliters = 250.0,
            aliases = listOf("latte", "caffe latte", "cafe latte"),
        ),
        CaffeineCatalogItem(
            id = "monster-energy-zero-sugar",
            name = "Monster Energy Zero Sugar",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 160.0,
            defaultServingMilliliters = 473.0,
        ),
        CaffeineCatalogItem(
            id = "coca-cola",
            name = "Coca-Cola",
            category = CaffeineSourceCategory.SODA,
            typicalCaffeineMg = 32.0,
            defaultServingMilliliters = 333.0,
            aliases = listOf("coke", "classic coke"),
        ),
        CaffeineCatalogItem(
            id = "tea-green",
            name = "Tea (Green)",
            category = CaffeineSourceCategory.TEA,
            typicalCaffeineMg = 36.0,
            defaultServingMilliliters = 240.0,
            aliases = listOf("green tea"),
        ),
        CaffeineCatalogItem(
            id = "green-tea",
            name = "Green Tea",
            category = CaffeineSourceCategory.TEA,
            typicalCaffeineMg = 34.0,
            defaultServingMilliliters = 200.0,
            aliases = listOf("tea green"),
        ),
        CaffeineCatalogItem(
            id = "dr-pepper",
            name = "Dr. Pepper",
            category = CaffeineSourceCategory.SODA,
            typicalCaffeineMg = 41.9965,
            defaultServingMilliliters = 355.0,
            aliases = listOf("dr pepper"),
        ),
        CaffeineCatalogItem(
            id = "diet-coke",
            name = "Diet Coke",
            category = CaffeineSourceCategory.SODA,
            typicalCaffeineMg = 46.01,
            defaultServingMilliliters = 355.0,
            aliases = listOf("coke diet"),
        ),
        CaffeineCatalogItem(
            id = "red-bull-zero",
            name = "Red Bull Zero",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 80.0,
            defaultServingMilliliters = 250.0,
        ),
        CaffeineCatalogItem(
            id = "starbucks-caffe-latte",
            name = "Starbucks Caffe Latte",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 66.0,
            defaultServingMilliliters = 354.0,
        ),
        CaffeineCatalogItem(
            id = "monster-energy",
            name = "Monster Energy",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 163.0,
            defaultServingMilliliters = 473.0,
            aliases = listOf("monster"),
        ),
        CaffeineCatalogItem(
            id = "matcha-tea",
            name = "Matcha Tea",
            category = CaffeineSourceCategory.TEA,
            typicalCaffeineMg = 64.0,
            defaultServingMilliliters = 240.0,
            aliases = listOf("matcha"),
        ),
        CaffeineCatalogItem(
            id = "red-bull-blue-edition",
            name = "Red Bull Blue Edition",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 80.0,
            defaultServingMilliliters = 250.0,
        ),
        CaffeineCatalogItem(
            id = "nescafe-gold",
            name = "Nescaf\u00e9 Gold",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 44.0,
            defaultServingMilliliters = 240.0,
        ),
        CaffeineCatalogItem(
            id = "pepsi-max",
            name = "Pepsi Max",
            category = CaffeineSourceCategory.SODA,
            typicalCaffeineMg = 45.8305,
            defaultServingMilliliters = 355.0,
        ),
        CaffeineCatalogItem(
            id = "celsius-sparkling-orange",
            name = "Celsius Sparkling Orange",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 200.0,
            defaultServingMilliliters = 355.0,
        ),
        CaffeineCatalogItem(
            id = "monster-energy-ultra-sunrise",
            name = "Monster Energy Ultra Sunrise",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 155.0,
            defaultServingMilliliters = 473.0,
        ),
        CaffeineCatalogItem(
            id = "nescafe-dolce-gusto-espresso-intenso",
            name = "Nescaf\u00e9 Dolce Gusto - Espresso Intenso",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 115.0,
            defaultServingMilliliters = 240.0,
        ),
        CaffeineCatalogItem(
            id = "costa-latte",
            name = "Costa Latte",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 100.0,
            defaultServingMilliliters = 354.0,
        ),
        CaffeineCatalogItem(
            id = "mountain-dew",
            name = "Mountain Dew",
            category = CaffeineSourceCategory.SODA,
            typicalCaffeineMg = 53.99,
            defaultServingMilliliters = 355.0,
            aliases = listOf("mtn dew"),
        ),
        CaffeineCatalogItem(
            id = "costa-cappuccino",
            name = "Costa Cappuccino",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 200.0,
            defaultServingMilliliters = 354.0,
        ),
        CaffeineCatalogItem(
            id = "mccafe-latte",
            name = "McCaf\u00e9 Latte",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 71.0,
            defaultServingMilliliters = 354.0,
        ),
        CaffeineCatalogItem(
            id = "fuze-tea",
            name = "Fuze Tea",
            category = CaffeineSourceCategory.TEA,
            typicalCaffeineMg = 11.999,
            defaultServingMilliliters = 355.0,
        ),
        CaffeineCatalogItem(
            id = "k-cup",
            name = "K-Cup",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 80.0,
            defaultServingMilliliters = 240.0,
        ),
        CaffeineCatalogItem(
            id = "c4-energy-drink",
            name = "C4 Energy drink",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 200.0,
            defaultServingMilliliters = 473.0,
        ),
        CaffeineCatalogItem(
            id = "monster-energy-ultra-peachy-keen",
            name = "Monster Energy Ultra Peachy Keen",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 150.0,
            defaultServingMilliliters = 473.0,
        ),
        CaffeineCatalogItem(
            id = "red-bull-sugarfree",
            name = "Red Bull Sugarfree",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 80.0,
            defaultServingMilliliters = 250.0,
        ),
        CaffeineCatalogItem(
            id = "caffe-nero-mocha-frappe-latte",
            name = "Caff\u00e9 Nero Mocha Frappe Latte",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 170.0,
            defaultServingMilliliters = 350.0,
        ),
        CaffeineCatalogItem(
            id = "dunkin-macchiato",
            name = "Dunkin' Macchiato",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 237.0,
            defaultServingMilliliters = 295.0,
        ),
        CaffeineCatalogItem(
            id = "monster-energy-mango-loco",
            name = "Monster Energy Mango Loco",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 150.0,
            defaultServingMilliliters = 473.0,
        ),
        CaffeineCatalogItem(
            id = "monster-energy-ultra-rosa",
            name = "Monster Energy Ultra Rosa",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 150.0,
            defaultServingMilliliters = 473.0,
        ),
        CaffeineCatalogItem(
            id = "starbucks-espresso",
            name = "Starbucks Espresso",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 33.0,
            defaultServingMilliliters = 33.0,
        ),
        CaffeineCatalogItem(
            id = "red-bull-coconut-edition",
            name = "Red Bull Coconut Edition",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 80.0,
            defaultServingMilliliters = 250.0,
        ),
        CaffeineCatalogItem(
            id = "cappuccino-double",
            name = "Cappuccino - Double",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 143.0,
            defaultServingMilliliters = 300.0,
        ),
        CaffeineCatalogItem(
            id = "bang-energy-drink",
            name = "Bang Energy Drink",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 300.0,
            defaultServingMilliliters = 500.0,
        ),
        CaffeineCatalogItem(
            id = "dunkin-iced-latte",
            name = "Dunkin' Iced Latte",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 166.0,
            defaultServingMilliliters = 709.0,
        ),
        CaffeineCatalogItem(
            id = "nescafe-dolce-gusto-espresso",
            name = "Nescaf\u00e9 Dolce Gusto - Espresso",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 80.0,
            defaultServingMilliliters = 240.0,
        ),
        CaffeineCatalogItem(
            id = "monster-energy-ultra-fiesta",
            name = "Monster Energy Ultra Fiesta",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 150.0,
            defaultServingMilliliters = 473.0,
        ),
        CaffeineCatalogItem(
            id = "dunkin-hot-chocolate",
            name = "Dunkin' Hot Chocolate",
            category = CaffeineSourceCategory.CHOCOLATE,
            typicalCaffeineMg = 13.0,
            defaultServingMilliliters = 414.0,
        ),
        CaffeineCatalogItem(
            id = "caffe-nero-americano",
            name = "Caff\u00e9 Nero Americano",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 160.0,
            defaultServingMilliliters = 350.0,
        ),
        CaffeineCatalogItem(
            id = "nescafe-dolce-gusto-cafe-au-lait",
            name = "Nescaf\u00e9 Dolce Gusto - Caf\u00e9 Au Lait",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 92.0,
            defaultServingMilliliters = 240.0,
        ),
        CaffeineCatalogItem(
            id = "pepsi-diet-cherry",
            name = "Pepsi Diet Cherry",
            category = CaffeineSourceCategory.SODA,
            typicalCaffeineMg = 40.5,
            defaultServingMilliliters = 354.0,
        ),
        CaffeineCatalogItem(
            id = "tea-jasmine",
            name = "Tea (Jasmine)",
            category = CaffeineSourceCategory.TEA,
            typicalCaffeineMg = 25.0,
            defaultServingMilliliters = 240.0,
        ),
        CaffeineCatalogItem(
            id = "faygo-cola",
            name = "Faygo Cola",
            category = CaffeineSourceCategory.SODA,
            typicalCaffeineMg = 41.7,
            defaultServingMilliliters = 354.0,
        ),
        CaffeineCatalogItem(
            id = "red-bull-red-edition",
            name = "Red Bull Red Edition",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 80.0,
            defaultServingMilliliters = 250.0,
        ),
        CaffeineCatalogItem(
            id = "starbucks-cafe-mocha",
            name = "Starbucks Caf\u00e9 Mocha",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 66.0,
            defaultServingMilliliters = 354.0,
        ),
        CaffeineCatalogItem(
            id = "dunkin-iced-tea",
            name = "Dunkin' Iced Tea",
            category = CaffeineSourceCategory.TEA,
            typicalCaffeineMg = 67.0,
            defaultServingMilliliters = 709.0,
        ),
        CaffeineCatalogItem(
            id = "hot-cocoa",
            name = "Hot Cocoa",
            category = CaffeineSourceCategory.CHOCOLATE,
            typicalCaffeineMg = 7.5,
            defaultServingMilliliters = 250.0,
            aliases = listOf("cocoa"),
        ),
        CaffeineCatalogItem(
            id = "monster-energy-pipeline-punch",
            name = "Monster Energy Pipeline Punch",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 160.0,
            defaultServingMilliliters = 473.0,
        ),
        CaffeineCatalogItem(
            id = "lipton-iced-tea",
            name = "Lipton Iced Tea",
            category = CaffeineSourceCategory.TEA,
            typicalCaffeineMg = 15.02,
            defaultServingMilliliters = 355.0,
        ),
        CaffeineCatalogItem(
            id = "monster-energy-rehab",
            name = "Monster Energy Rehab",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 160.0,
            defaultServingMilliliters = 473.0,
        ),
        CaffeineCatalogItem(
            id = "red-bull-peach-edition",
            name = "Red Bull Peach Edition",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 80.0,
            defaultServingMilliliters = 250.0,
        ),
        CaffeineCatalogItem(
            id = "monster-energy-reserve",
            name = "Monster Energy Reserve",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 160.0,
            defaultServingMilliliters = 473.0,
        ),
        CaffeineCatalogItem(
            id = "red-bull-summer-edition",
            name = "Red Bull Summer Edition",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 80.0,
            defaultServingMilliliters = 250.0,
        ),
        CaffeineCatalogItem(
            id = "monster-energy-ultra-gold",
            name = "Monster Energy Ultra Gold",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 150.0,
            defaultServingMilliliters = 473.0,
        ),
        CaffeineCatalogItem(
            id = "monster-energy-juice",
            name = "Monster Energy Juice",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 160.0,
            defaultServingMilliliters = 473.0,
        ),
        CaffeineCatalogItem(
            id = "celsius-sparkling-grapefruit",
            name = "Celsius Sparkling Grapefruit",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 200.0,
            defaultServingMilliliters = 355.0,
        ),
        CaffeineCatalogItem(
            id = "dark-chocolate-70-85",
            name = "Dark Chocolate (70-85%)",
            category = CaffeineSourceCategory.CHOCOLATE,
            typicalCaffeineMg = 8.0,
            aliases = listOf("dark chocolate"),
        ),
        CaffeineCatalogItem(
            id = "mccafe-americano",
            name = "McCaf\u00e9 Americano",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 71.0,
            defaultServingMilliliters = 354.0,
        ),
        CaffeineCatalogItem(
            id = "starbucks-caramel-macchiato",
            name = "Starbucks Caramel Macchiato",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 66.0,
            defaultServingMilliliters = 354.0,
        ),
        CaffeineCatalogItem(
            id = "v8-energy-strawberry-banana",
            name = "V8+ Energy Strawberry Banana",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 80.0,
            defaultServingMilliliters = 237.0,
        ),
        CaffeineCatalogItem(
            id = "starbucks-cappuccino",
            name = "Starbucks Cappuccino",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 66.0,
            defaultServingMilliliters = 354.0,
        ),
        CaffeineCatalogItem(
            id = "hell-energy-drink",
            name = "Hell Energy Drink",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 80.0,
            defaultServingMilliliters = 250.0,
        ),
        CaffeineCatalogItem(
            id = "monster-energy-mega-drink",
            name = "Monster Energy Mega Drink",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 240.0,
            defaultServingMilliliters = 710.0,
        ),
        CaffeineCatalogItem(
            id = "monster-energy-ultra-blue",
            name = "Monster Energy Ultra Blue",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 150.0,
            defaultServingMilliliters = 473.0,
        ),
        CaffeineCatalogItem(
            id = "nescafe-dolce-gusto-cafe-au-lait-intenso",
            name = "Nescaf\u00e9 Dolce Gusto - Caf\u00e9 Au Lait Intenso",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 102.0,
            defaultServingMilliliters = 240.0,
        ),
        CaffeineCatalogItem(
            id = "nescafe-dolce-gusto-caffe-grande-intenso",
            name = "Nescaf\u00e9 Dolce Gusto - Caffe Grande Intenso",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 130.0,
            defaultServingMilliliters = 240.0,
        ),
        CaffeineCatalogItem(
            id = "nestea",
            name = "Nestea",
            category = CaffeineSourceCategory.TEA,
            typicalCaffeineMg = 16.33,
            defaultServingMilliliters = 355.0,
        ),
        CaffeineCatalogItem(
            id = "pepsi-cherry",
            name = "Pepsi Cherry",
            category = CaffeineSourceCategory.SODA,
            typicalCaffeineMg = 39.7,
            defaultServingMilliliters = 354.0,
        ),
        CaffeineCatalogItem(
            id = "red-bull-tropical-edition",
            name = "Red Bull Tropical Edition",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 80.0,
            defaultServingMilliliters = 250.0,
        ),
        CaffeineCatalogItem(
            id = "costa-americano",
            name = "Costa Americano",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 200.0,
            defaultServingMilliliters = 354.0,
        ),
        CaffeineCatalogItem(
            id = "monster-energy-assault",
            name = "Monster Energy Assault",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 160.0,
            defaultServingMilliliters = 473.0,
        ),
        CaffeineCatalogItem(
            id = "monster-energy-nitro",
            name = "Monster Energy Nitro",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 160.0,
            defaultServingMilliliters = 473.0,
        ),
        CaffeineCatalogItem(
            id = "monster-energy-ultra-violet",
            name = "Monster Energy Ultra Violet",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 140.0,
            defaultServingMilliliters = 473.0,
        ),
        CaffeineCatalogItem(
            id = "monster-energy-ultra-watermelon",
            name = "Monster Energy Ultra Watermelon",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 150.0,
            defaultServingMilliliters = 473.0,
        ),
        CaffeineCatalogItem(
            id = "starbucks-flat-white",
            name = "Starbucks Flat White",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 66.0,
            defaultServingMilliliters = 236.0,
        ),
        CaffeineCatalogItem(
            id = "monster-energy-import",
            name = "Monster Energy Import",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 179.0,
            defaultServingMilliliters = 550.0,
        ),
        CaffeineCatalogItem(
            id = "monster-energy-ultra-paradise",
            name = "Monster Energy Ultra Paradise",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 140.0,
            defaultServingMilliliters = 473.0,
        ),
        CaffeineCatalogItem(
            id = "tea-herbal",
            name = "Tea (Herbal)",
            category = CaffeineSourceCategory.TEA,
            typicalCaffeineMg = 0.0,
            defaultServingMilliliters = 240.0,
        ),
        CaffeineCatalogItem(
            id = "v8-energy-sparkling-lemon-lime",
            name = "V8+ Energy Sparkling Lemon Lime",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 80.0,
            defaultServingMilliliters = 355.0,
        ),
        CaffeineCatalogItem(
            id = "burn",
            name = "Burn",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 113.6,
            defaultServingMilliliters = 355.0,
        ),
        CaffeineCatalogItem(
            id = "caffe-nero-espresso-macchiato",
            name = "Caff\u00e9 Nero Espresso Macchiato",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 80.0,
            defaultServingMilliliters = 350.0,
        ),
        CaffeineCatalogItem(
            id = "celsius-peach-mango-green-tea",
            name = "Celsius Peach Mango Green Tea",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 200.0,
            defaultServingMilliliters = 355.0,
        ),
        CaffeineCatalogItem(
            id = "coca-cola-cherry",
            name = "Coca-Cola Cherry",
            category = CaffeineSourceCategory.SODA,
            typicalCaffeineMg = 34.4,
            defaultServingMilliliters = 354.0,
        ),
        CaffeineCatalogItem(
            id = "coca-cola-diet-cherry",
            name = "Coca-Cola Diet Cherry",
            category = CaffeineSourceCategory.SODA,
            typicalCaffeineMg = 35.0,
            defaultServingMilliliters = 354.0,
        ),
        CaffeineCatalogItem(
            id = "costa-flat-white",
            name = "Costa Flat White",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 241.0,
            defaultServingMilliliters = 354.0,
        ),
        CaffeineCatalogItem(
            id = "coca-cola-light",
            name = "Coca-Cola Light",
            category = CaffeineSourceCategory.SODA,
            typicalCaffeineMg = 46.01,
            defaultServingMilliliters = 355.0,
        ),
        CaffeineCatalogItem(
            id = "dunkin-latte",
            name = "Dunkin' Latte",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 166.0,
            defaultServingMilliliters = 414.0,
        ),
        CaffeineCatalogItem(
            id = "mccafe-mocha",
            name = "McCaf\u00e9 Mocha",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 86.0,
            defaultServingMilliliters = 354.0,
        ),
        CaffeineCatalogItem(
            id = "red-bull-green-edition",
            name = "Red Bull Green Edition",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 80.0,
            defaultServingMilliliters = 250.0,
        ),
        CaffeineCatalogItem(
            id = "28-black-energy-drink",
            name = "28 Black Energy Drink",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 125.0,
            defaultServingMilliliters = 250.0,
        ),
        CaffeineCatalogItem(
            id = "caffe-nero-caffe-latte",
            name = "Caff\u00e9 Nero Caff\u00e9 Latte",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 160.0,
            defaultServingMilliliters = 350.0,
        ),
        CaffeineCatalogItem(
            id = "carabao-energy-drink",
            name = "Carabao Energy Drink",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 106.0,
            defaultServingMilliliters = 330.0,
        ),
        CaffeineCatalogItem(
            id = "dark-chocolate-60-69",
            name = "Dark Chocolate (60-69%)",
            category = CaffeineSourceCategory.CHOCOLATE,
            typicalCaffeineMg = 8.6,
        ),
        CaffeineCatalogItem(
            id = "dunkin-matcha-latte",
            name = "Dunkin' Matcha Latte",
            category = CaffeineSourceCategory.TEA,
            typicalCaffeineMg = 90.0,
            defaultServingMilliliters = 414.0,
        ),
        CaffeineCatalogItem(
            id = "dunkin-vanilla-chai",
            name = "Dunkin' Vanilla Chai",
            category = CaffeineSourceCategory.TEA,
            typicalCaffeineMg = 80.0,
            defaultServingMilliliters = 414.0,
        ),
        CaffeineCatalogItem(
            id = "monster-energy-java",
            name = "Monster Energy Java",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 200.0,
            defaultServingMilliliters = 444.0,
        ),
        CaffeineCatalogItem(
            id = "nescafe-3-in-1-instant-coffee",
            name = "Nescaf\u00e9 3 in 1 Instant Coffee",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 50.0,
            defaultServingMilliliters = 240.0,
        ),
        CaffeineCatalogItem(
            id = "nescafe-dolce-gusto-capuccino",
            name = "Nescaf\u00e9 Dolce Gusto - Capuccino",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 107.0,
            defaultServingMilliliters = 240.0,
        ),
        CaffeineCatalogItem(
            id = "v8-energy-diet-strawberry-lemonade",
            name = "V8+ Energy Diet Strawberry Lemonade",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 80.0,
            defaultServingMilliliters = 237.0,
        ),
        CaffeineCatalogItem(
            id = "caffe-nero-frappe-latte",
            name = "Caff\u00e9 Nero Frappe Latte",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 160.0,
            defaultServingMilliliters = 350.0,
        ),
        CaffeineCatalogItem(
            id = "caffe-nero-iced-latte",
            name = "Caff\u00e9 Nero Iced Latte",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 160.0,
            defaultServingMilliliters = 350.0,
        ),
        CaffeineCatalogItem(
            id = "caffe-nero-mocha",
            name = "Caff\u00e9 Nero Mocha",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 170.0,
            defaultServingMilliliters = 350.0,
        ),
        CaffeineCatalogItem(
            id = "dark-chocolate-45-59",
            name = "Dark Chocolate (45-59%)",
            category = CaffeineSourceCategory.CHOCOLATE,
            typicalCaffeineMg = 4.3,
        ),
        CaffeineCatalogItem(
            id = "mccafe-caramel-macchiato",
            name = "McCaf\u00e9 Caramel Macchiato",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 71.0,
            defaultServingMilliliters = 354.0,
        ),
        CaffeineCatalogItem(
            id = "prime-energy-drink",
            name = "Prime Energy Drink",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 200.0,
            defaultServingMilliliters = 473.0,
        ),
        CaffeineCatalogItem(
            id = "starbucks-white-mocha",
            name = "Starbucks White Mocha",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 66.0,
            defaultServingMilliliters = 354.0,
        ),
        CaffeineCatalogItem(
            id = "swiss-miss-hot-chocolate",
            name = "Swiss Miss Hot Chocolate",
            category = CaffeineSourceCategory.CHOCOLATE,
            typicalCaffeineMg = 6.0,
            defaultServingMilliliters = 240.0,
        ),
        CaffeineCatalogItem(
            id = "v8-energy-peach-mango",
            name = "V8+ Energy Peach Mango",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 80.0,
            defaultServingMilliliters = 237.0,
        ),
        CaffeineCatalogItem(
            id = "caffe-nero-espresso",
            name = "Caff\u00e9 Nero Espresso",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 80.0,
            defaultServingMilliliters = 350.0,
        ),
        CaffeineCatalogItem(
            id = "dunkin-iced-macchiato",
            name = "Dunkin' Iced Macchiato",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 284.0,
            defaultServingMilliliters = 709.0,
        ),
        CaffeineCatalogItem(
            id = "nescafe-dolce-gusto-latte-macchiato",
            name = "Nescaf\u00e9 Dolce Gusto - Latte Macchiato",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 85.0,
            defaultServingMilliliters = 240.0,
        ),
        CaffeineCatalogItem(
            id = "shasta-cola",
            name = "Shasta Cola",
            category = CaffeineSourceCategory.SODA,
            typicalCaffeineMg = 42.9,
            defaultServingMilliliters = 354.0,
        ),
        CaffeineCatalogItem(
            id = "v8-energy-orange-pineapple",
            name = "V8+ Energy Orange Pineapple",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 80.0,
            defaultServingMilliliters = 237.0,
        ),
        CaffeineCatalogItem(
            id = "3d-energy-drink",
            name = "3D Energy",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 200.0,
            defaultServingMilliliters = 473.0,
        ),
        CaffeineCatalogItem(
            id = "celsius-sparkling-watermelon",
            name = "Celsius Sparkling Watermelon",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 200.0,
            defaultServingMilliliters = 355.0,
        ),
        CaffeineCatalogItem(
            id = "dunkin-espresso",
            name = "Dunkin' Espresso",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 118.0,
            defaultServingMilliliters = 295.0,
        ),
        CaffeineCatalogItem(
            id = "monster-energy-java-300",
            name = "Monster Energy Java 300",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 300.0,
            defaultServingMilliliters = 444.0,
        ),
        CaffeineCatalogItem(
            id = "monster-energy-ultra-black",
            name = "Monster Energy Ultra Black",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 150.0,
            defaultServingMilliliters = 473.0,
        ),
        CaffeineCatalogItem(
            id = "monster-energy-ultra-red",
            name = "Monster Energy Ultra Red",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 140.0,
            defaultServingMilliliters = 473.0,
        ),
        CaffeineCatalogItem(
            id = "mountain-dew-code-red",
            name = "Mountain Dew Code Red",
            category = CaffeineSourceCategory.SODA,
            typicalCaffeineMg = 54.03,
            defaultServingMilliliters = 355.0,
        ),
        CaffeineCatalogItem(
            id = "nescafe-dolce-gusto-lungo-intenso",
            name = "Nescaf\u00e9 Dolce Gusto - Lungo Intenso",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 147.0,
            defaultServingMilliliters = 240.0,
        ),
        CaffeineCatalogItem(
            id = "v8-energy-tropical-green",
            name = "V8+ Energy Tropical Green",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 80.0,
            defaultServingMilliliters = 237.0,
        ),
        CaffeineCatalogItem(
            id = "big-shock",
            name = "Big Shock!",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 114.6,
            defaultServingMilliliters = 355.0,
        ),
        CaffeineCatalogItem(
            id = "blue-tokai-attikan-estate",
            name = "Blue Tokai Attikan Estate",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 60.0,
            defaultServingMilliliters = 35.0,
        ),
        CaffeineCatalogItem(
            id = "blue-tokai-dhak-blend",
            name = "Blue Tokai Dhak Blend",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 60.0,
            defaultServingMilliliters = 35.0,
        ),
        CaffeineCatalogItem(
            id = "blue-tokai-silver-oak-blend",
            name = "Blue Tokai Silver Oak Blend",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 60.0,
            defaultServingMilliliters = 35.0,
        ),
        CaffeineCatalogItem(
            id = "blue-tokai-vienna-roast",
            name = "Blue Tokai Vienna Roast",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 60.0,
            defaultServingMilliliters = 35.0,
        ),
        CaffeineCatalogItem(
            id = "caffeine-powder",
            name = "Caffeine powder",
            category = CaffeineSourceCategory.SUPPLEMENT,
            typicalCaffeineMg = 1000.0,
            aliases = listOf("caffeine powder"),
        ),
        CaffeineCatalogItem(
            id = "celsius-inferno-punch",
            name = "Celsius Inferno Punch",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 300.0,
            defaultServingMilliliters = 473.0,
        ),
        CaffeineCatalogItem(
            id = "celsius-tart-cherry-lime",
            name = "Celsius Tart Cherry Lime",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 100.0,
            defaultServingMilliliters = 355.0,
        ),
        CaffeineCatalogItem(
            id = "dunkin-americano",
            name = "Dunkin' Americano",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 237.0,
            defaultServingMilliliters = 295.0,
        ),
        CaffeineCatalogItem(
            id = "dunkin-hot-tea",
            name = "Dunkin' Hot Tea",
            category = CaffeineSourceCategory.TEA,
            typicalCaffeineMg = 90.0,
            defaultServingMilliliters = 414.0,
        ),
        CaffeineCatalogItem(
            id = "excedrin",
            name = "Excedrin",
            category = CaffeineSourceCategory.SUPPLEMENT,
            typicalCaffeineMg = 65.0,
        ),
        CaffeineCatalogItem(
            id = "irish-tea",
            name = "Irish Tea",
            category = CaffeineSourceCategory.TEA,
            typicalCaffeineMg = 50.0,
            defaultServingMilliliters = 240.0,
        ),
        CaffeineCatalogItem(
            id = "kopi-peng",
            name = "Kopi Peng",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 95.0,
            defaultServingMilliliters = 240.0,
        ),
        CaffeineCatalogItem(
            id = "mccafe-cappuccino",
            name = "McCaf\u00e9 Cappuccino",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 71.0,
            defaultServingMilliliters = 354.0,
        ),
        CaffeineCatalogItem(
            id = "mccafe-caramel-cappuccino",
            name = "McCaf\u00e9 Caramel Cappuccino",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 71.0,
            defaultServingMilliliters = 354.0,
        ),
        CaffeineCatalogItem(
            id = "merrild-red",
            name = "Merrild Red",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 96.0,
            defaultServingMilliliters = 240.0,
        ),
        CaffeineCatalogItem(
            id = "merrild-special",
            name = "Merrild Special",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 95.0,
            defaultServingMilliliters = 240.0,
        ),
        CaffeineCatalogItem(
            id = "nescafe-dolce-gusto-capuccino-skinny",
            name = "Nescaf\u00e9 Dolce Gusto - Capuccino Skinny",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 90.0,
            defaultServingMilliliters = 240.0,
        ),
        CaffeineCatalogItem(
            id = "nescafe-dolce-gusto-lungo",
            name = "Nescaf\u00e9 Dolce Gusto - Lungo",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 89.0,
            defaultServingMilliliters = 240.0,
        ),
        CaffeineCatalogItem(
            id = "nespresso-classic-pod-110-ml",
            name = "Nespresso Classic Pod (110 ml)",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 95.0,
            defaultServingMilliliters = 240.0,
        ),
        CaffeineCatalogItem(
            id = "nespresso-classic-pod-25-ml",
            name = "Nespresso Classic Pod (25 ml)",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 60.0,
            defaultServingMilliliters = 25.0,
        ),
        CaffeineCatalogItem(
            id = "nespresso-classic-pod-40-ml",
            name = "Nespresso Classic Pod (40 ml)",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 80.0,
            defaultServingMilliliters = 40.0,
        ),
        CaffeineCatalogItem(
            id = "nocco-bcaa",
            name = "Nocco BCAA",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 180.0,
            defaultServingMilliliters = 330.0,
        ),
        CaffeineCatalogItem(
            id = "nocco-focus",
            name = "Nocco Focus",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 180.0,
            defaultServingMilliliters = 330.0,
        ),
        CaffeineCatalogItem(
            id = "paulaner-spezi",
            name = "Paulaner Spezi",
            category = CaffeineSourceCategory.SODA,
            typicalCaffeineMg = 33.0,
            defaultServingMilliliters = 500.0,
        ),
        CaffeineCatalogItem(
            id = "peter-larsen-kaffe-fairtrade",
            name = "Peter Larsen Kaffe Fairtrade",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 95.0,
            defaultServingMilliliters = 240.0,
        ),
        CaffeineCatalogItem(
            id = "peter-larsen-kaffe-original-72",
            name = "Peter Larsen Kaffe Original 72",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 95.0,
            defaultServingMilliliters = 240.0,
        ),
        CaffeineCatalogItem(
            id = "red-bull-winter-edition",
            name = "Red Bull Winter Edition",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 80.0,
            defaultServingMilliliters = 250.0,
        ),
        CaffeineCatalogItem(
            id = "reign",
            name = "Reign (US)",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 300.0,
            defaultServingMilliliters = 473.0,
        ),
        CaffeineCatalogItem(
            id = "reign-uk",
            name = "Reign (UK)",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 200.0,
            defaultServingMilliliters = 500.0,
        ),
        CaffeineCatalogItem(
            id = "starbucks-iced-caff-latte",
            name = "Starbucks Iced Caff\u00e8 Latte",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 75.0,
            defaultServingMilliliters = 355.0,
        ),
        CaffeineCatalogItem(
            id = "turkish-coffee",
            name = "Turkish Coffee",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 50.7,
            defaultServingMilliliters = 60.0,
        ),
        CaffeineCatalogItem(
            id = "vivarin-caffeine-pill",
            name = "Vivarin",
            category = CaffeineSourceCategory.SUPPLEMENT,
            typicalCaffeineMg = 200.0,
        ),
        CaffeineCatalogItem(
            id = "yerba-mat-tea",
            name = "Yerba Mat\u00e9 (Tea)",
            category = CaffeineSourceCategory.TEA,
            typicalCaffeineMg = 40.0,
            defaultServingMilliliters = 240.0,
        ),
        CaffeineCatalogItem(
            id = "5-hour-energy-extra-strength",
            name = "5 Hour Energy Extra Strength",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 230.0,
            defaultServingMilliliters = 57.0,
        ),
        CaffeineCatalogItem(
            id = "atkins-iced-coffee-protein-shake",
            name = "Atkins Iced Coffee Protein Shake",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 70.0,
            defaultServingMilliliters = 240.0,
        ),
        CaffeineCatalogItem(
            id = "caffe-nero-cappuccino",
            name = "Caff\u00e9 Nero Cappuccino",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 160.0,
            defaultServingMilliliters = 350.0,
        ),
        CaffeineCatalogItem(
            id = "caffe-nero-espresso-con-panna",
            name = "Caff\u00e9 Nero Espresso Con Panna",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 80.0,
            defaultServingMilliliters = 350.0,
        ),
        CaffeineCatalogItem(
            id = "celsius-blood-orange-lemonade",
            name = "Celsius Blood Orange Lemonade",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 100.0,
            defaultServingMilliliters = 355.0,
        ),
        CaffeineCatalogItem(
            id = "celsius-jackfruit",
            name = "Celsius Jackfruit",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 300.0,
            defaultServingMilliliters = 473.0,
        ),
        CaffeineCatalogItem(
            id = "cheerwine",
            name = "Cheerwine",
            category = CaffeineSourceCategory.SODA,
            typicalCaffeineMg = 47.5,
            defaultServingMilliliters = 354.0,
        ),
        CaffeineCatalogItem(
            id = "cheerwine-diet",
            name = "Cheerwine Diet",
            category = CaffeineSourceCategory.SODA,
            typicalCaffeineMg = 48.1,
            defaultServingMilliliters = 354.0,
        ),
        CaffeineCatalogItem(
            id = "coca-cola-diet-cherry-1",
            name = "Coca-Cola Diet Cherry",
            category = CaffeineSourceCategory.SODA,
            typicalCaffeineMg = 35.0,
            defaultServingMilliliters = 354.0,
        ),
        CaffeineCatalogItem(
            id = "crystal-light",
            name = "Crystal Light",
            category = CaffeineSourceCategory.SODA,
            typicalCaffeineMg = 30.0,
            defaultServingMilliliters = 240.0,
        ),
        CaffeineCatalogItem(
            id = "dunkin-cappuccino",
            name = "Dunkin' Cappuccino",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 166.0,
            defaultServingMilliliters = 414.0,
        ),
        CaffeineCatalogItem(
            id = "dunkin-dunkaccino",
            name = "Dunkin' Dunkaccino",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 85.0,
            defaultServingMilliliters = 414.0,
        ),
        CaffeineCatalogItem(
            id = "eternal-energy",
            name = "Eternal Energy",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 190.0,
            defaultServingMilliliters = 59.0,
        ),
        CaffeineCatalogItem(
            id = "fast-twitch",
            name = "Fast Twitch",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 200.0,
            defaultServingMilliliters = 355.0,
        ),
        CaffeineCatalogItem(
            id = "full-throttle",
            name = "Full Throttle",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 160.0,
            defaultServingMilliliters = 473.0,
        ),
        CaffeineCatalogItem(
            id = "gamersups",
            name = "Gamersups",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 100.0,
            defaultServingMilliliters = 240.0,
        ),
        CaffeineCatalogItem(
            id = "generic-caffeine-pill",
            name = "Generic Caffeine Pill",
            category = CaffeineSourceCategory.SUPPLEMENT,
            typicalCaffeineMg = 200.0,
            aliases = listOf("caffeine pill", "caffeine tablet"),
        ),
        CaffeineCatalogItem(
            id = "ghost",
            name = "Ghost",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 200.0,
            defaultServingMilliliters = 473.0,
        ),
        CaffeineCatalogItem(
            id = "gorgie",
            name = "Gorgie",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 120.0,
            defaultServingMilliliters = 355.0,
        ),
        CaffeineCatalogItem(
            id = "gorilla-mind-energy-drink",
            name = "Gorilla Mind Energy Drink",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 200.0,
            defaultServingMilliliters = 355.0,
        ),
        CaffeineCatalogItem(
            id = "gorilla-mode-preworkout",
            name = "Gorilla Mode Pre-workout",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 350.0,
            defaultServingMilliliters = 240.0,
        ),
        CaffeineCatalogItem(
            id = "guayak-yerba-mate",
            name = "Guayak\u00ed Yerba Mate",
            category = CaffeineSourceCategory.TEA,
            typicalCaffeineMg = 150.0,
            defaultServingMilliliters = 458.0,
        ),
        CaffeineCatalogItem(
            id = "hell-ice-coffee",
            name = "Hell Ice Coffee",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 38.0,
            defaultServingMilliliters = 240.0,
        ),
        CaffeineCatalogItem(
            id = "jet-alert-caffeine-pill",
            name = "Jet Alert Caffeine Pill",
            category = CaffeineSourceCategory.SUPPLEMENT,
            typicalCaffeineMg = 100.0,
        ),
        CaffeineCatalogItem(
            id = "jocko-go",
            name = "Jocko GO",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 95.0,
            defaultServingMilliliters = 355.0,
        ),
        CaffeineCatalogItem(
            id = "kirkland-breakfast-blend",
            name = "Kirkland Breakfast Blend",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 98.0,
            defaultServingMilliliters = 240.0,
        ),
        CaffeineCatalogItem(
            id = "kofola",
            name = "Kofola",
            category = CaffeineSourceCategory.SODA,
            typicalCaffeineMg = 53.25,
            defaultServingMilliliters = 355.0,
        ),
        CaffeineCatalogItem(
            id = "lucky-energy",
            name = "Lucky Energy",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 80.0,
            defaultServingMilliliters = 250.0,
        ),
        CaffeineCatalogItem(
            id = "madmonq",
            name = "MADMONQ",
            category = CaffeineSourceCategory.SUPPLEMENT,
            typicalCaffeineMg = 155.0,
        ),
        CaffeineCatalogItem(
            id = "mio-energy",
            name = "Mio Energy",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 60.0,
            defaultServingMilliliters = 240.0,
        ),
        CaffeineCatalogItem(
            id = "monster-energy-mule",
            name = "Monster Energy Mule",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 160.0,
            defaultServingMilliliters = 473.0,
        ),
        CaffeineCatalogItem(
            id = "mountain-dew-kickstart",
            name = "Mountain Dew Kickstart",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 90.0,
            defaultServingMilliliters = 473.0,
        ),
        CaffeineCatalogItem(
            id = "nescafe-ice-java",
            name = "Nescaf\u00e9 Ice Java",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 60.0,
            defaultServingMilliliters = 15.0,
        ),
        CaffeineCatalogItem(
            id = "nespresso-vertuo-pod-150-ml",
            name = "Nespresso Vertuo Pod (150 ml)",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 150.0,
            defaultServingMilliliters = 150.0,
        ),
        CaffeineCatalogItem(
            id = "nespresso-vertuo-pod-230-ml",
            name = "Nespresso Vertuo Pod (230 ml)",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 177.0,
            defaultServingMilliliters = 240.0,
        ),
        CaffeineCatalogItem(
            id = "nespresso-vertuo-pod-230-ml-20-caffeine",
            name = "Nespresso Vertuo Pod (230 ml, +20% Caffeine)",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 200.0,
            defaultServingMilliliters = 230.0,
        ),
        CaffeineCatalogItem(
            id = "nespresso-vertuo-pod-25-ml",
            name = "Nespresso Vertuo Pod (25 ml)",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 60.0,
            defaultServingMilliliters = 25.0,
        ),
        CaffeineCatalogItem(
            id = "nespresso-vertuo-pod-40-ml",
            name = "Nespresso Vertuo Pod (40 ml)",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 60.0,
            defaultServingMilliliters = 40.0,
        ),
        CaffeineCatalogItem(
            id = "nodoz-caffeine-pill",
            name = "NoDoz Caffeine Pill",
            category = CaffeineSourceCategory.SUPPLEMENT,
            typicalCaffeineMg = 200.0,
        ),
        CaffeineCatalogItem(
            id = "oca-energy-drink",
            name = "Oca",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 120.0,
            defaultServingMilliliters = 355.0,
        ),
        CaffeineCatalogItem(
            id = "old-town-white-coffee",
            name = "Old Town White coffee",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 60.0,
            defaultServingMilliliters = 240.0,
        ),
        CaffeineCatalogItem(
            id = "rip-it-citrus-x",
            name = "Rip It Citrus X",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 160.0,
            defaultServingMilliliters = 473.0,
        ),
        CaffeineCatalogItem(
            id = "semtex",
            name = "Semtex",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 113.6,
            defaultServingMilliliters = 355.0,
        ),
        CaffeineCatalogItem(
            id = "solo-energy-drink",
            name = "Solo Energy Drink",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 32.0,
            defaultServingMilliliters = 100.0,
        ),
        CaffeineCatalogItem(
            id = "suntory-boss-iced-long-black",
            name = "Suntory Boss Iced Long Black",
            category = CaffeineSourceCategory.COFFEE,
            typicalCaffeineMg = 140.0,
            defaultServingMilliliters = 237.0,
        ),
        CaffeineCatalogItem(
            id = "true-north-home",
            name = "True North Home",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 120.0,
            defaultServingMilliliters = 355.0,
        ),
        CaffeineCatalogItem(
            id = "twist-energy-drink",
            name = "Twist Energy Drink",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 80.0,
            defaultServingMilliliters = 250.0,
        ),
        CaffeineCatalogItem(
            id = "v8-energy-black-cherry",
            name = "V8+ Energy Black Cherry",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 80.0,
            defaultServingMilliliters = 237.0,
        ),
        CaffeineCatalogItem(
            id = "v8-energy-diet-cranberry-raspberry",
            name = "V8+ Energy Diet Cranberry Raspberry",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 80.0,
            defaultServingMilliliters = 237.0,
        ),
        CaffeineCatalogItem(
            id = "v8-energy-honeycrisp-apple-berry",
            name = "V8+ Energy Honeycrisp Apple Berry",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 80.0,
            defaultServingMilliliters = 237.0,
        ),
        CaffeineCatalogItem(
            id = "v8-energy-pomegranate-blueberry",
            name = "V8+ Energy Pomegranate Blueberry",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 80.0,
            defaultServingMilliliters = 237.0,
        ),
        CaffeineCatalogItem(
            id = "v8-energy-sparkling-black-cherry",
            name = "V8+ Energy Sparkling Black Cherry",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 80.0,
            defaultServingMilliliters = 355.0,
        ),
        CaffeineCatalogItem(
            id = "v8-energy-sparkling-orange-pineapple",
            name = "V8+ Energy Sparkling Orange Pineapple",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 80.0,
            defaultServingMilliliters = 355.0,
        ),
        CaffeineCatalogItem(
            id = "v8-energy-sparkling-strawberry-kiwi",
            name = "V8+ Energy Sparkling Strawberry Kiwi",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 80.0,
            defaultServingMilliliters = 355.0,
        ),
        CaffeineCatalogItem(
            id = "wooooo-energy-drink",
            name = "Wooooo! Energy Drink",
            category = CaffeineSourceCategory.ENERGY_DRINK,
            typicalCaffeineMg = 200.0,
            defaultServingMilliliters = 473.0,
        ),
    )

    private data class NormalizedItem(
        val item: CaffeineCatalogItem,
        val aliases: List<String>,
    )

    private val normalizedItems: List<NormalizedItem> by lazy(LazyThreadSafetyMode.PUBLICATION) {
        items.map { item ->
            val aliases = (listOf(item.name, item.id.replace('-', ' ')) + item.aliases)
                .map(::normalize)
                .filter(String::isNotBlank)
                .distinct()
                .sortedByDescending(String::length)
            NormalizedItem(item = item, aliases = aliases)
        }
    }
    private val itemsById: Map<String, CaffeineCatalogItem> by lazy(LazyThreadSafetyMode.PUBLICATION) {
        items.associateBy { it.id }
    }

    fun beveragePresets(): List<CustomHydrationDrink> =
        items.asSequence()
            .filter { item -> item.defaultServingMilliliters != null }
            .filterNot { item -> item.category == CaffeineSourceCategory.SUPPLEMENT }
            .map { item ->
                CustomHydrationDrink(
                    id = "$BeveragePresetIdPrefix${item.id}",
                    name = item.name,
                    volumeMilliliters = item.defaultServingMilliliters ?: 240.0,
                    hydrationMultiplier = 1.0,
                    nutrientValues = BeverageNutritionDefaults.nutrientValuesFor(item),
                    category = item.category,
                    isPreloaded = true,
                )
            }
            .toList()

    fun beveragePresetItem(presetId: String): CaffeineCatalogItem? {
        if (!presetId.startsWith(BeveragePresetIdPrefix)) return null
        return itemsById[presetId.removePrefix(BeveragePresetIdPrefix)]
    }

    fun match(entry: CaffeineEntry): CaffeineCatalogMatch? =
        matchName(entry.name)

    fun matchName(name: String?): CaffeineCatalogMatch? {
        val normalized = normalize(name.orEmpty())
        if (normalized.isBlank()) return null

        normalizedItems.forEach { candidate ->
            val exact = candidate.aliases.firstOrNull { it == normalized }
            if (exact != null) {
                return CaffeineCatalogMatch(
                    item = candidate.item,
                    confidence = CaffeineCatalogMatchConfidence.EXACT,
                    matchedText = exact,
                )
            }
        }

        normalizedItems
            .asSequence()
            .flatMap { candidate -> candidate.aliases.asSequence().map { alias -> candidate to alias } }
            .filter { (_, alias) -> alias.length >= 3 && phraseContains(normalized, alias) }
            .maxByOrNull { (_, alias) -> alias.length }
            ?.let { (candidate, alias) ->
                return CaffeineCatalogMatch(
                    item = candidate.item,
                    confidence = if (alias in candidate.item.aliases.map(::normalize)) {
                        CaffeineCatalogMatchConfidence.ALIAS
                    } else {
                        CaffeineCatalogMatchConfidence.CONTAINS
                    },
                    matchedText = alias,
                )
            }

        return null
    }

    fun categoryFor(entry: CaffeineEntry): CaffeineSourceCategory =
        match(entry)?.item?.category ?: inferGenericCategory(entry.name)

    fun inferGenericCategory(name: String?): CaffeineSourceCategory {
        val normalized = normalize(name.orEmpty())
        return when {
            containsAny(normalized, "espresso", "coffee", "latte", "cappuccino", "americano", "cold brew", "mocha", "macchiato", "frappe", "nespresso") -> CaffeineSourceCategory.COFFEE
            containsAny(normalized, "tea", "matcha", "chai", "yerba", "mate") -> CaffeineSourceCategory.TEA
            containsAny(normalized, "energy", "red bull", "redbull", "monster", "celsius", "rockstar", "bang", "c4", "pre workout", "preworkout") -> CaffeineSourceCategory.ENERGY_DRINK
            containsAny(normalized, "cola", "soda", "pepsi", "coke", "dr pepper", "mountain dew", "mtn dew") -> CaffeineSourceCategory.SODA
            containsAny(normalized, "chocolate", "cocoa", "cacao") -> CaffeineSourceCategory.CHOCOLATE
            containsAny(normalized, "pill", "tablet", "capsule", "powder", "supplement", "excedrin", "nodoz") -> CaffeineSourceCategory.SUPPLEMENT
            else -> CaffeineSourceCategory.OTHER
        }
    }

    private fun phraseContains(value: String, phrase: String): Boolean =
        " $value ".contains(" $phrase ")

    private fun containsAny(value: String, vararg needles: String): Boolean =
        needles.any { phraseContains(value, normalize(it)) }

    private fun normalize(value: String): String =
        Normalizer.normalize(value.lowercase(Locale.ROOT), Normalizer.Form.NFD)
            .replace(CombiningMarks, "")
            .replace(NonAlphaNumeric, " ")
            .trim()
}
