// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package tech.mmarca.openvitals.health_connect_native

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

enum class BodyMeasurementTypeMsg(val raw: Int) {
  WEIGHT(0),
  HEIGHT(1),
  BODY_FAT(2);

  companion object {
    fun ofRaw(raw: Int): BodyMeasurementTypeMsg? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Raw Health Connect availability signals, mapped to the Dart
 * `HealthConnectAvailability` enum on the Flutter side. Kept as separate
 * signals (rather than a native enum) so the enum stays a single source of
 * truth in Dart.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class HealthConnectAvailabilityDetail (
  /** Raw `HealthConnectClient.getSdkStatus` int. */
  val sdkStatus: Long,
  /**
   * True when running in a work/managed profile where Health Connect is
   * unsupported (Android 13+).
   */
  val unsupportedProfile: Boolean,
  /**
   * True when the standalone Health Connect APK is installed on Android 13-
   * but the Play Store is not (so it can never be updated).
   */
  val standaloneNeedsPlayStore: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): HealthConnectAvailabilityDetail {
      val sdkStatus = pigeonVar_list[0] as Long
      val unsupportedProfile = pigeonVar_list[1] as Boolean
      val standaloneNeedsPlayStore = pigeonVar_list[2] as Boolean
      return HealthConnectAvailabilityDetail(sdkStatus, unsupportedProfile, standaloneNeedsPlayStore)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      sdkStatus,
      unsupportedProfile,
      standaloneNeedsPlayStore,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as HealthConnectAvailabilityDetail
    return MessagesPigeonUtils.deepEquals(this.sdkStatus, other.sdkStatus) && MessagesPigeonUtils.deepEquals(this.unsupportedProfile, other.unsupportedProfile) && MessagesPigeonUtils.deepEquals(this.standaloneNeedsPlayStore, other.standaloneNeedsPlayStore)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.sdkStatus)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.unsupportedProfile)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.standaloneNeedsPlayStore)
    return result
  }
  override fun toString(): String {
    return "HealthConnectAvailabilityDetail(sdkStatus=$sdkStatus, unsupportedProfile=$unsupportedProfile, standaloneNeedsPlayStore=$standaloneNeedsPlayStore)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class WeightEntryMsg (
  val timeEpochMs: Long,
  val weightKg: Double,
  val source: String,
  val id: String,
  val isOpenVitalsEntry: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): WeightEntryMsg {
      val timeEpochMs = pigeonVar_list[0] as Long
      val weightKg = pigeonVar_list[1] as Double
      val source = pigeonVar_list[2] as String
      val id = pigeonVar_list[3] as String
      val isOpenVitalsEntry = pigeonVar_list[4] as Boolean
      return WeightEntryMsg(timeEpochMs, weightKg, source, id, isOpenVitalsEntry)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      timeEpochMs,
      weightKg,
      source,
      id,
      isOpenVitalsEntry,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as WeightEntryMsg
    return MessagesPigeonUtils.deepEquals(this.timeEpochMs, other.timeEpochMs) && MessagesPigeonUtils.deepEquals(this.weightKg, other.weightKg) && MessagesPigeonUtils.deepEquals(this.source, other.source) && MessagesPigeonUtils.deepEquals(this.id, other.id) && MessagesPigeonUtils.deepEquals(this.isOpenVitalsEntry, other.isOpenVitalsEntry)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.timeEpochMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.weightKg)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.source)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.id)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.isOpenVitalsEntry)
    return result
  }
  override fun toString(): String {
    return "WeightEntryMsg(timeEpochMs=$timeEpochMs, weightKg=$weightKg, source=$source, id=$id, isOpenVitalsEntry=$isOpenVitalsEntry)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class HeightEntryMsg (
  val timeEpochMs: Long,
  val heightCm: Double,
  val source: String,
  val id: String,
  val isOpenVitalsEntry: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): HeightEntryMsg {
      val timeEpochMs = pigeonVar_list[0] as Long
      val heightCm = pigeonVar_list[1] as Double
      val source = pigeonVar_list[2] as String
      val id = pigeonVar_list[3] as String
      val isOpenVitalsEntry = pigeonVar_list[4] as Boolean
      return HeightEntryMsg(timeEpochMs, heightCm, source, id, isOpenVitalsEntry)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      timeEpochMs,
      heightCm,
      source,
      id,
      isOpenVitalsEntry,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as HeightEntryMsg
    return MessagesPigeonUtils.deepEquals(this.timeEpochMs, other.timeEpochMs) && MessagesPigeonUtils.deepEquals(this.heightCm, other.heightCm) && MessagesPigeonUtils.deepEquals(this.source, other.source) && MessagesPigeonUtils.deepEquals(this.id, other.id) && MessagesPigeonUtils.deepEquals(this.isOpenVitalsEntry, other.isOpenVitalsEntry)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.timeEpochMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.heightCm)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.source)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.id)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.isOpenVitalsEntry)
    return result
  }
  override fun toString(): String {
    return "HeightEntryMsg(timeEpochMs=$timeEpochMs, heightCm=$heightCm, source=$source, id=$id, isOpenVitalsEntry=$isOpenVitalsEntry)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BodyFatEntryMsg (
  val timeEpochMs: Long,
  val percent: Double,
  val source: String,
  val id: String,
  val isOpenVitalsEntry: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BodyFatEntryMsg {
      val timeEpochMs = pigeonVar_list[0] as Long
      val percent = pigeonVar_list[1] as Double
      val source = pigeonVar_list[2] as String
      val id = pigeonVar_list[3] as String
      val isOpenVitalsEntry = pigeonVar_list[4] as Boolean
      return BodyFatEntryMsg(timeEpochMs, percent, source, id, isOpenVitalsEntry)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      timeEpochMs,
      percent,
      source,
      id,
      isOpenVitalsEntry,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BodyFatEntryMsg
    return MessagesPigeonUtils.deepEquals(this.timeEpochMs, other.timeEpochMs) && MessagesPigeonUtils.deepEquals(this.percent, other.percent) && MessagesPigeonUtils.deepEquals(this.source, other.source) && MessagesPigeonUtils.deepEquals(this.id, other.id) && MessagesPigeonUtils.deepEquals(this.isOpenVitalsEntry, other.isOpenVitalsEntry)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.timeEpochMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.percent)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.source)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.id)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.isOpenVitalsEntry)
    return result
  }
  override fun toString(): String {
    return "BodyFatEntryMsg(timeEpochMs=$timeEpochMs, percent=$percent, source=$source, id=$id, isOpenVitalsEntry=$isOpenVitalsEntry)"
  }
}

/**
 * Shared shape for LeanBodyMass / BoneMass / BodyWaterMass entries.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class BodyMassEntryMsg (
  val timeEpochMs: Long,
  val massKg: Double,
  val source: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BodyMassEntryMsg {
      val timeEpochMs = pigeonVar_list[0] as Long
      val massKg = pigeonVar_list[1] as Double
      val source = pigeonVar_list[2] as String
      return BodyMassEntryMsg(timeEpochMs, massKg, source)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      timeEpochMs,
      massKg,
      source,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BodyMassEntryMsg
    return MessagesPigeonUtils.deepEquals(this.timeEpochMs, other.timeEpochMs) && MessagesPigeonUtils.deepEquals(this.massKg, other.massKg) && MessagesPigeonUtils.deepEquals(this.source, other.source)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.timeEpochMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.massKg)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.source)
    return result
  }
  override fun toString(): String {
    return "BodyMassEntryMsg(timeEpochMs=$timeEpochMs, massKg=$massKg, source=$source)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BmrEntryMsg (
  val timeEpochMs: Long,
  val kcalPerDay: Double,
  val source: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BmrEntryMsg {
      val timeEpochMs = pigeonVar_list[0] as Long
      val kcalPerDay = pigeonVar_list[1] as Double
      val source = pigeonVar_list[2] as String
      return BmrEntryMsg(timeEpochMs, kcalPerDay, source)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      timeEpochMs,
      kcalPerDay,
      source,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BmrEntryMsg
    return MessagesPigeonUtils.deepEquals(this.timeEpochMs, other.timeEpochMs) && MessagesPigeonUtils.deepEquals(this.kcalPerDay, other.kcalPerDay) && MessagesPigeonUtils.deepEquals(this.source, other.source)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.timeEpochMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.kcalPerDay)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.source)
    return result
  }
  override fun toString(): String {
    return "BmrEntryMsg(timeEpochMs=$timeEpochMs, kcalPerDay=$kcalPerDay, source=$source)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BodyMeasurementEntryMsg (
  val id: String,
  val type: BodyMeasurementTypeMsg,
  val timeEpochMs: Long,
  val value: Double,
  val source: String,
  val isOpenVitalsEntry: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BodyMeasurementEntryMsg {
      val id = pigeonVar_list[0] as String
      val type = pigeonVar_list[1] as BodyMeasurementTypeMsg
      val timeEpochMs = pigeonVar_list[2] as Long
      val value = pigeonVar_list[3] as Double
      val source = pigeonVar_list[4] as String
      val isOpenVitalsEntry = pigeonVar_list[5] as Boolean
      return BodyMeasurementEntryMsg(id, type, timeEpochMs, value, source, isOpenVitalsEntry)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      type,
      timeEpochMs,
      value,
      source,
      isOpenVitalsEntry,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BodyMeasurementEntryMsg
    return MessagesPigeonUtils.deepEquals(this.id, other.id) && MessagesPigeonUtils.deepEquals(this.type, other.type) && MessagesPigeonUtils.deepEquals(this.timeEpochMs, other.timeEpochMs) && MessagesPigeonUtils.deepEquals(this.value, other.value) && MessagesPigeonUtils.deepEquals(this.source, other.source) && MessagesPigeonUtils.deepEquals(this.isOpenVitalsEntry, other.isOpenVitalsEntry)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.id)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.type)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.timeEpochMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.value)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.source)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.isOpenVitalsEntry)
    return result
  }
  override fun toString(): String {
    return "BodyMeasurementEntryMsg(id=$id, type=$type, timeEpochMs=$timeEpochMs, value=$value, source=$source, isOpenVitalsEntry=$isOpenVitalsEntry)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BodyMeasurementWriteRequestMsg (
  val type: BodyMeasurementTypeMsg,
  val timeEpochMs: Long,
  val value: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BodyMeasurementWriteRequestMsg {
      val type = pigeonVar_list[0] as BodyMeasurementTypeMsg
      val timeEpochMs = pigeonVar_list[1] as Long
      val value = pigeonVar_list[2] as Double
      return BodyMeasurementWriteRequestMsg(type, timeEpochMs, value)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      type,
      timeEpochMs,
      value,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BodyMeasurementWriteRequestMsg
    return MessagesPigeonUtils.deepEquals(this.type, other.type) && MessagesPigeonUtils.deepEquals(this.timeEpochMs, other.timeEpochMs) && MessagesPigeonUtils.deepEquals(this.value, other.value)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.type)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.timeEpochMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.value)
    return result
  }
  override fun toString(): String {
    return "BodyMeasurementWriteRequestMsg(type=$type, timeEpochMs=$timeEpochMs, value=$value)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class HydrationEntryMsg (
  val startEpochMs: Long,
  val endEpochMs: Long,
  val liters: Double,
  val source: String,
  val id: String,
  val clientRecordId: String? = null,
  val isOpenVitalsEntry: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): HydrationEntryMsg {
      val startEpochMs = pigeonVar_list[0] as Long
      val endEpochMs = pigeonVar_list[1] as Long
      val liters = pigeonVar_list[2] as Double
      val source = pigeonVar_list[3] as String
      val id = pigeonVar_list[4] as String
      val clientRecordId = pigeonVar_list[5] as String?
      val isOpenVitalsEntry = pigeonVar_list[6] as Boolean
      return HydrationEntryMsg(startEpochMs, endEpochMs, liters, source, id, clientRecordId, isOpenVitalsEntry)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      startEpochMs,
      endEpochMs,
      liters,
      source,
      id,
      clientRecordId,
      isOpenVitalsEntry,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as HydrationEntryMsg
    return MessagesPigeonUtils.deepEquals(this.startEpochMs, other.startEpochMs) && MessagesPigeonUtils.deepEquals(this.endEpochMs, other.endEpochMs) && MessagesPigeonUtils.deepEquals(this.liters, other.liters) && MessagesPigeonUtils.deepEquals(this.source, other.source) && MessagesPigeonUtils.deepEquals(this.id, other.id) && MessagesPigeonUtils.deepEquals(this.clientRecordId, other.clientRecordId) && MessagesPigeonUtils.deepEquals(this.isOpenVitalsEntry, other.isOpenVitalsEntry)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.startEpochMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.endEpochMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.liters)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.source)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.id)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.clientRecordId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.isOpenVitalsEntry)
    return result
  }
  override fun toString(): String {
    return "HydrationEntryMsg(startEpochMs=$startEpochMs, endEpochMs=$endEpochMs, liters=$liters, source=$source, id=$id, clientRecordId=$clientRecordId, isOpenVitalsEntry=$isOpenVitalsEntry)"
  }
}

/**
 * One daily hydration total; [dateEpochMs] is local midnight of the day.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class DailyHydrationMsg (
  val dateEpochMs: Long,
  val liters: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DailyHydrationMsg {
      val dateEpochMs = pigeonVar_list[0] as Long
      val liters = pigeonVar_list[1] as Double
      return DailyHydrationMsg(dateEpochMs, liters)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      dateEpochMs,
      liters,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as DailyHydrationMsg
    return MessagesPigeonUtils.deepEquals(this.dateEpochMs, other.dateEpochMs) && MessagesPigeonUtils.deepEquals(this.liters, other.liters)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.dateEpochMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.liters)
    return result
  }
  override fun toString(): String {
    return "DailyHydrationMsg(dateEpochMs=$dateEpochMs, liters=$liters)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class HydrationWriteRequestMsg (
  val timeEpochMs: Long,
  val volumeLiters: Double,
  val drinkId: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): HydrationWriteRequestMsg {
      val timeEpochMs = pigeonVar_list[0] as Long
      val volumeLiters = pigeonVar_list[1] as Double
      val drinkId = pigeonVar_list[2] as String?
      return HydrationWriteRequestMsg(timeEpochMs, volumeLiters, drinkId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      timeEpochMs,
      volumeLiters,
      drinkId,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as HydrationWriteRequestMsg
    return MessagesPigeonUtils.deepEquals(this.timeEpochMs, other.timeEpochMs) && MessagesPigeonUtils.deepEquals(this.volumeLiters, other.volumeLiters) && MessagesPigeonUtils.deepEquals(this.drinkId, other.drinkId)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.timeEpochMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.volumeLiters)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.drinkId)
    return result
  }
  override fun toString(): String {
    return "HydrationWriteRequestMsg(timeEpochMs=$timeEpochMs, volumeLiters=$volumeLiters, drinkId=$drinkId)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MindfulnessSessionMsg (
  val id: String,
  val title: String? = null,
  val startEpochMs: Long,
  val endEpochMs: Long,
  val durationMs: Long,
  val source: String,
  val isOpenVitalsEntry: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MindfulnessSessionMsg {
      val id = pigeonVar_list[0] as String
      val title = pigeonVar_list[1] as String?
      val startEpochMs = pigeonVar_list[2] as Long
      val endEpochMs = pigeonVar_list[3] as Long
      val durationMs = pigeonVar_list[4] as Long
      val source = pigeonVar_list[5] as String
      val isOpenVitalsEntry = pigeonVar_list[6] as Boolean
      return MindfulnessSessionMsg(id, title, startEpochMs, endEpochMs, durationMs, source, isOpenVitalsEntry)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      title,
      startEpochMs,
      endEpochMs,
      durationMs,
      source,
      isOpenVitalsEntry,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as MindfulnessSessionMsg
    return MessagesPigeonUtils.deepEquals(this.id, other.id) && MessagesPigeonUtils.deepEquals(this.title, other.title) && MessagesPigeonUtils.deepEquals(this.startEpochMs, other.startEpochMs) && MessagesPigeonUtils.deepEquals(this.endEpochMs, other.endEpochMs) && MessagesPigeonUtils.deepEquals(this.durationMs, other.durationMs) && MessagesPigeonUtils.deepEquals(this.source, other.source) && MessagesPigeonUtils.deepEquals(this.isOpenVitalsEntry, other.isOpenVitalsEntry)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.id)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.title)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.startEpochMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.endEpochMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.durationMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.source)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.isOpenVitalsEntry)
    return result
  }
  override fun toString(): String {
    return "MindfulnessSessionMsg(id=$id, title=$title, startEpochMs=$startEpochMs, endEpochMs=$endEpochMs, durationMs=$durationMs, source=$source, isOpenVitalsEntry=$isOpenVitalsEntry)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MindfulnessSessionWriteRequestMsg (
  val title: String,
  val startEpochMs: Long,
  val endEpochMs: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MindfulnessSessionWriteRequestMsg {
      val title = pigeonVar_list[0] as String
      val startEpochMs = pigeonVar_list[1] as Long
      val endEpochMs = pigeonVar_list[2] as Long
      return MindfulnessSessionWriteRequestMsg(title, startEpochMs, endEpochMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      title,
      startEpochMs,
      endEpochMs,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as MindfulnessSessionWriteRequestMsg
    return MessagesPigeonUtils.deepEquals(this.title, other.title) && MessagesPigeonUtils.deepEquals(this.startEpochMs, other.startEpochMs) && MessagesPigeonUtils.deepEquals(this.endEpochMs, other.endEpochMs)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.title)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.startEpochMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.endEpochMs)
    return result
  }
  override fun toString(): String {
    return "MindfulnessSessionWriteRequestMsg(title=$title, startEpochMs=$startEpochMs, endEpochMs=$endEpochMs)"
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          BodyMeasurementTypeMsg.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          HealthConnectAvailabilityDetail.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          WeightEntryMsg.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          HeightEntryMsg.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BodyFatEntryMsg.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BodyMassEntryMsg.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BmrEntryMsg.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BodyMeasurementEntryMsg.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BodyMeasurementWriteRequestMsg.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          HydrationEntryMsg.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DailyHydrationMsg.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          HydrationWriteRequestMsg.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MindfulnessSessionMsg.fromList(it)
        }
      }
      142.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MindfulnessSessionWriteRequestMsg.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is BodyMeasurementTypeMsg -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is HealthConnectAvailabilityDetail -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is WeightEntryMsg -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is HeightEntryMsg -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is BodyFatEntryMsg -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is BodyMassEntryMsg -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is BmrEntryMsg -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is BodyMeasurementEntryMsg -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is BodyMeasurementWriteRequestMsg -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is HydrationEntryMsg -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is DailyHydrationMsg -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is HydrationWriteRequestMsg -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is MindfulnessSessionMsg -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      is MindfulnessSessionWriteRequestMsg -> {
        stream.write(142)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Host (Android/Kotlin) API surface backed by `HealthConnectClient`.
 *
 * All record payloads are JSON strings; see the record JSON schema in
 * `lib/health_connect_native.dart`. Permission strings are Health Connect
 * permission identifiers (e.g. `android.permission.health.READ_STEPS`).
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface HealthConnectHostApi {
  /**
   * Maps to `HealthConnectClient.getSdkStatus(context)`.
   *
   * Returns the raw SDK status int (e.g. `SDK_AVAILABLE`,
   * `SDK_UNAVAILABLE`, `SDK_UNAVAILABLE_PROVIDER_UPDATE_REQUIRED`).
   */
  fun getSdkStatus(): Long
  /**
   * Fuller availability picture than [getSdkStatus]: SDK status plus the
   * work-profile and standalone-needs-Play-Store overrides, so Dart can resolve
   * NOT_SUPPORTED / NEEDS_PLAY_STORE / NEEDS_PROVIDER_UPDATE / AVAILABLE.
   */
  fun availabilityDetail(): HealthConnectAvailabilityDetail
  /**
   * Mirrors the user's "pause Health Connect sync" toggle into the native
   * sync-gate. While disabled, reads short-circuit to empty and writes throw.
   */
  fun setSyncEnabled(enabled: Boolean)
  /** Returns the native sync-gate's current state. */
  fun getSyncEnabled(): Boolean
  /** Returns the subset of [permissions] currently granted. */
  fun getGrantedPermissions(permissions: List<String>, callback: (Result<List<String>>) -> Unit)
  /**
   * Launches the Health Connect permission contract via the Activity and
   * resolves to whether every requested permission ended up granted.
   */
  fun requestPermissions(permissions: List<String>, callback: (Result<Boolean>) -> Unit)
  /**
   * Opens the Health Connect page for this app (app-specific permission
   * management on Android 14+, falling back to Health Connect settings) so the
   * user can manually grant permissions the runtime dialog reports as
   * non-requestable (e.g. planned exercise, exercise routes, background/history
   * access). Returns whether a page was launched.
   */
  fun openHealthConnectSettings(callback: (Result<Boolean>) -> Unit)
  /**
   * Whether an optional Health Connect feature is available on this device,
   * e.g. `"SKIN_TEMPERATURE"`, `"MINDFULNESS_SESSION"`, `"PLANNED_EXERCISE"`.
   */
  fun isFeatureAvailable(feature: String, callback: (Result<Boolean>) -> Unit)
  /**
   * Reads records of [recordType] in the [startEpochMs, endEpochMs] window,
   * returning one JSON object (as a String) per record. [filterJson] is an
   * optional JSON object carrying extra read constraints (data origins,
   * paging, ascending/descending, page size, etc.).
   */
  fun readRecordsJson(recordType: String, startEpochMs: Long, endEpochMs: Long, filterJson: String?, callback: (Result<List<String>>) -> Unit)
  /**
   * Reads a single record of [recordType] by its Health Connect [recordId],
   * or `null` if it does not exist.
   */
  fun readRecordJson(recordType: String, recordId: String, callback: (Result<String?>) -> Unit)
  /**
   * Runs an aggregation over [aggregateMetrics] in the given window, returning
   * a metric-key -> value map (value is `null` when Health Connect has no data
   * for that metric in the window).
   */
  fun aggregate(aggregateMetrics: List<String>, startEpochMs: Long, endEpochMs: Long, callback: (Result<Map<String, Double?>>) -> Unit)
  /**
   * Aggregates [aggregateMetrics] grouped into buckets of [bucketType]
   * (e.g. `"DAYS"`, `"WEEKS"`, `"MONTHS"`), returning one JSON object (as a
   * String) per bucket with its time range and aggregated values.
   */
  fun aggregateGroupByPeriodJson(aggregateMetrics: List<String>, startEpochMs: Long, endEpochMs: Long, bucketType: String, callback: (Result<List<String>>) -> Unit)
  /**
   * Inserts the given records (each a JSON object String matching the canonical
   * schema) and returns the inserted Health Connect record ids in order.
   */
  fun insertRecordsJson(recordsJson: List<String>, callback: (Result<List<String>>) -> Unit)
  /** Deletes records of [recordType] by their app-assigned client record ids. */
  fun deleteRecordsByClientIds(recordType: String, clientRecordIds: List<String>, callback: (Result<Unit>) -> Unit)
  /** Deletes records of [recordType] by their Health Connect record ids. */
  fun deleteRecordsByIds(recordType: String, recordIds: List<String>, callback: (Result<Unit>) -> Unit)
  /**
   * Import dedup helper: of the supplied [clientRecordIds], returns the subset
   * that ALREADY exist in Health Connect for [recordType].
   */
  fun filterExistingClientIds(recordType: String, clientRecordIds: List<String>, callback: (Result<List<String>>) -> Unit)
  fun readWeightEntries(startEpochMs: Long, endEpochMs: Long, callback: (Result<List<WeightEntryMsg>>) -> Unit)
  fun readLatestWeight(callback: (Result<WeightEntryMsg?>) -> Unit)
  fun readHeightEntries(startEpochMs: Long, endEpochMs: Long, callback: (Result<List<HeightEntryMsg>>) -> Unit)
  fun readLatestHeightEntry(callback: (Result<HeightEntryMsg?>) -> Unit)
  fun readBodyFatEntries(startEpochMs: Long, endEpochMs: Long, callback: (Result<List<BodyFatEntryMsg>>) -> Unit)
  fun readLatestBodyFat(callback: (Result<BodyFatEntryMsg?>) -> Unit)
  fun readLeanBodyMassEntries(startEpochMs: Long, endEpochMs: Long, callback: (Result<List<BodyMassEntryMsg>>) -> Unit)
  fun readLatestLeanBodyMass(callback: (Result<BodyMassEntryMsg?>) -> Unit)
  fun readBmrEntries(startEpochMs: Long, endEpochMs: Long, callback: (Result<List<BmrEntryMsg>>) -> Unit)
  fun readLatestBmr(callback: (Result<BmrEntryMsg?>) -> Unit)
  fun readBoneMassEntries(startEpochMs: Long, endEpochMs: Long, callback: (Result<List<BodyMassEntryMsg>>) -> Unit)
  fun readLatestBoneMass(callback: (Result<BodyMassEntryMsg?>) -> Unit)
  fun readBodyWaterMassEntries(startEpochMs: Long, endEpochMs: Long, callback: (Result<List<BodyMassEntryMsg>>) -> Unit)
  fun readLatestBodyWaterMass(callback: (Result<BodyMassEntryMsg?>) -> Unit)
  fun writeBodyMeasurementEntry(request: BodyMeasurementWriteRequestMsg, callback: (Result<String>) -> Unit)
  fun readBodyMeasurementEntry(type: BodyMeasurementTypeMsg, id: String, callback: (Result<BodyMeasurementEntryMsg?>) -> Unit)
  fun updateBodyMeasurementEntry(id: String, request: BodyMeasurementWriteRequestMsg, callback: (Result<Unit>) -> Unit)
  fun deleteBodyMeasurementEntry(type: BodyMeasurementTypeMsg, id: String, callback: (Result<Unit>) -> Unit)
  fun readHydrationLiters(startEpochMs: Long, endEpochMs: Long, callback: (Result<Double?>) -> Unit)
  fun readDailyHydration(startEpochMs: Long, endEpochMs: Long, callback: (Result<List<DailyHydrationMsg>>) -> Unit)
  fun readHydrationEntries(startEpochMs: Long, endEpochMs: Long, callback: (Result<List<HydrationEntryMsg>>) -> Unit)
  fun readHydrationEntry(id: String, callback: (Result<HydrationEntryMsg?>) -> Unit)
  fun writeHydrationEntry(request: HydrationWriteRequestMsg, callback: (Result<String>) -> Unit)
  fun updateHydrationEntry(id: String, request: HydrationWriteRequestMsg, callback: (Result<Unit>) -> Unit)
  fun deleteHydrationEntry(id: String, callback: (Result<String?>) -> Unit)
  fun readMindfulnessSessions(startEpochMs: Long, endEpochMs: Long, callback: (Result<List<MindfulnessSessionMsg>>) -> Unit)
  fun readMindfulnessSession(id: String, callback: (Result<MindfulnessSessionMsg?>) -> Unit)
  fun readMindfulnessMinutes(startEpochMs: Long, endEpochMs: Long, callback: (Result<Long>) -> Unit)
  fun writeMindfulnessSessionEntry(request: MindfulnessSessionWriteRequestMsg, callback: (Result<String>) -> Unit)
  fun updateMindfulnessSessionEntry(id: String, request: MindfulnessSessionWriteRequestMsg, callback: (Result<Unit>) -> Unit)
  fun deleteMindfulnessSessionEntry(id: String, callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by HealthConnectHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `HealthConnectHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: HealthConnectHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.getSdkStatus$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getSdkStatus())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.availabilityDetail$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.availabilityDetail())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.setSyncEnabled$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val enabledArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.setSyncEnabled(enabledArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.getSyncEnabled$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getSyncEnabled())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.getGrantedPermissions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val permissionsArg = args[0] as List<String>
            api.getGrantedPermissions(permissionsArg) { result: Result<List<String>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.requestPermissions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val permissionsArg = args[0] as List<String>
            api.requestPermissions(permissionsArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.openHealthConnectSettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.openHealthConnectSettings{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.isFeatureAvailable$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val featureArg = args[0] as String
            api.isFeatureAvailable(featureArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.readRecordsJson$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val recordTypeArg = args[0] as String
            val startEpochMsArg = args[1] as Long
            val endEpochMsArg = args[2] as Long
            val filterJsonArg = args[3] as String?
            api.readRecordsJson(recordTypeArg, startEpochMsArg, endEpochMsArg, filterJsonArg) { result: Result<List<String>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.readRecordJson$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val recordTypeArg = args[0] as String
            val recordIdArg = args[1] as String
            api.readRecordJson(recordTypeArg, recordIdArg) { result: Result<String?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.aggregate$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val aggregateMetricsArg = args[0] as List<String>
            val startEpochMsArg = args[1] as Long
            val endEpochMsArg = args[2] as Long
            api.aggregate(aggregateMetricsArg, startEpochMsArg, endEpochMsArg) { result: Result<Map<String, Double?>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.aggregateGroupByPeriodJson$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val aggregateMetricsArg = args[0] as List<String>
            val startEpochMsArg = args[1] as Long
            val endEpochMsArg = args[2] as Long
            val bucketTypeArg = args[3] as String
            api.aggregateGroupByPeriodJson(aggregateMetricsArg, startEpochMsArg, endEpochMsArg, bucketTypeArg) { result: Result<List<String>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.insertRecordsJson$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val recordsJsonArg = args[0] as List<String>
            api.insertRecordsJson(recordsJsonArg) { result: Result<List<String>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.deleteRecordsByClientIds$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val recordTypeArg = args[0] as String
            val clientRecordIdsArg = args[1] as List<String>
            api.deleteRecordsByClientIds(recordTypeArg, clientRecordIdsArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.deleteRecordsByIds$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val recordTypeArg = args[0] as String
            val recordIdsArg = args[1] as List<String>
            api.deleteRecordsByIds(recordTypeArg, recordIdsArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.filterExistingClientIds$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val recordTypeArg = args[0] as String
            val clientRecordIdsArg = args[1] as List<String>
            api.filterExistingClientIds(recordTypeArg, clientRecordIdsArg) { result: Result<List<String>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.readWeightEntries$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val startEpochMsArg = args[0] as Long
            val endEpochMsArg = args[1] as Long
            api.readWeightEntries(startEpochMsArg, endEpochMsArg) { result: Result<List<WeightEntryMsg>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.readLatestWeight$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.readLatestWeight{ result: Result<WeightEntryMsg?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.readHeightEntries$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val startEpochMsArg = args[0] as Long
            val endEpochMsArg = args[1] as Long
            api.readHeightEntries(startEpochMsArg, endEpochMsArg) { result: Result<List<HeightEntryMsg>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.readLatestHeightEntry$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.readLatestHeightEntry{ result: Result<HeightEntryMsg?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.readBodyFatEntries$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val startEpochMsArg = args[0] as Long
            val endEpochMsArg = args[1] as Long
            api.readBodyFatEntries(startEpochMsArg, endEpochMsArg) { result: Result<List<BodyFatEntryMsg>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.readLatestBodyFat$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.readLatestBodyFat{ result: Result<BodyFatEntryMsg?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.readLeanBodyMassEntries$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val startEpochMsArg = args[0] as Long
            val endEpochMsArg = args[1] as Long
            api.readLeanBodyMassEntries(startEpochMsArg, endEpochMsArg) { result: Result<List<BodyMassEntryMsg>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.readLatestLeanBodyMass$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.readLatestLeanBodyMass{ result: Result<BodyMassEntryMsg?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.readBmrEntries$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val startEpochMsArg = args[0] as Long
            val endEpochMsArg = args[1] as Long
            api.readBmrEntries(startEpochMsArg, endEpochMsArg) { result: Result<List<BmrEntryMsg>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.readLatestBmr$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.readLatestBmr{ result: Result<BmrEntryMsg?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.readBoneMassEntries$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val startEpochMsArg = args[0] as Long
            val endEpochMsArg = args[1] as Long
            api.readBoneMassEntries(startEpochMsArg, endEpochMsArg) { result: Result<List<BodyMassEntryMsg>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.readLatestBoneMass$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.readLatestBoneMass{ result: Result<BodyMassEntryMsg?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.readBodyWaterMassEntries$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val startEpochMsArg = args[0] as Long
            val endEpochMsArg = args[1] as Long
            api.readBodyWaterMassEntries(startEpochMsArg, endEpochMsArg) { result: Result<List<BodyMassEntryMsg>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.readLatestBodyWaterMass$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.readLatestBodyWaterMass{ result: Result<BodyMassEntryMsg?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.writeBodyMeasurementEntry$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as BodyMeasurementWriteRequestMsg
            api.writeBodyMeasurementEntry(requestArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.readBodyMeasurementEntry$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val typeArg = args[0] as BodyMeasurementTypeMsg
            val idArg = args[1] as String
            api.readBodyMeasurementEntry(typeArg, idArg) { result: Result<BodyMeasurementEntryMsg?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.updateBodyMeasurementEntry$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as String
            val requestArg = args[1] as BodyMeasurementWriteRequestMsg
            api.updateBodyMeasurementEntry(idArg, requestArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.deleteBodyMeasurementEntry$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val typeArg = args[0] as BodyMeasurementTypeMsg
            val idArg = args[1] as String
            api.deleteBodyMeasurementEntry(typeArg, idArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.readHydrationLiters$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val startEpochMsArg = args[0] as Long
            val endEpochMsArg = args[1] as Long
            api.readHydrationLiters(startEpochMsArg, endEpochMsArg) { result: Result<Double?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.readDailyHydration$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val startEpochMsArg = args[0] as Long
            val endEpochMsArg = args[1] as Long
            api.readDailyHydration(startEpochMsArg, endEpochMsArg) { result: Result<List<DailyHydrationMsg>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.readHydrationEntries$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val startEpochMsArg = args[0] as Long
            val endEpochMsArg = args[1] as Long
            api.readHydrationEntries(startEpochMsArg, endEpochMsArg) { result: Result<List<HydrationEntryMsg>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.readHydrationEntry$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as String
            api.readHydrationEntry(idArg) { result: Result<HydrationEntryMsg?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.writeHydrationEntry$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as HydrationWriteRequestMsg
            api.writeHydrationEntry(requestArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.updateHydrationEntry$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as String
            val requestArg = args[1] as HydrationWriteRequestMsg
            api.updateHydrationEntry(idArg, requestArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.deleteHydrationEntry$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as String
            api.deleteHydrationEntry(idArg) { result: Result<String?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.readMindfulnessSessions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val startEpochMsArg = args[0] as Long
            val endEpochMsArg = args[1] as Long
            api.readMindfulnessSessions(startEpochMsArg, endEpochMsArg) { result: Result<List<MindfulnessSessionMsg>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.readMindfulnessSession$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as String
            api.readMindfulnessSession(idArg) { result: Result<MindfulnessSessionMsg?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.readMindfulnessMinutes$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val startEpochMsArg = args[0] as Long
            val endEpochMsArg = args[1] as Long
            api.readMindfulnessMinutes(startEpochMsArg, endEpochMsArg) { result: Result<Long> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.writeMindfulnessSessionEntry$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as MindfulnessSessionWriteRequestMsg
            api.writeMindfulnessSessionEntry(requestArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.updateMindfulnessSessionEntry$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as String
            val requestArg = args[1] as MindfulnessSessionWriteRequestMsg
            api.updateMindfulnessSessionEntry(idArg, requestArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.deleteMindfulnessSessionEntry$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as String
            api.deleteMindfulnessSessionEntry(idArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
