// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package tech.mmarca.openvitals.health_connect_native

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return     super.readValueOfType(type, buffer)
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    super.writeValue(stream, value)
  }
}


/**
 * Host (Android/Kotlin) API surface backed by `HealthConnectClient`.
 *
 * All record payloads are JSON strings; see the record JSON schema in
 * `lib/health_connect_native.dart`. Permission strings are Health Connect
 * permission identifiers (e.g. `android.permission.health.READ_STEPS`).
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface HealthConnectHostApi {
  /**
   * Maps to `HealthConnectClient.getSdkStatus(context)`.
   *
   * Returns the raw SDK status int (e.g. `SDK_AVAILABLE`,
   * `SDK_UNAVAILABLE`, `SDK_UNAVAILABLE_PROVIDER_UPDATE_REQUIRED`).
   */
  fun getSdkStatus(): Long
  /** Returns the subset of [permissions] currently granted. */
  fun getGrantedPermissions(permissions: List<String>, callback: (Result<List<String>>) -> Unit)
  /**
   * Launches the Health Connect permission contract via the Activity and
   * resolves to whether every requested permission ended up granted.
   */
  fun requestPermissions(permissions: List<String>, callback: (Result<Boolean>) -> Unit)
  /**
   * Whether an optional Health Connect feature is available on this device,
   * e.g. `"SKIN_TEMPERATURE"`, `"MINDFULNESS_SESSION"`, `"PLANNED_EXERCISE"`.
   */
  fun isFeatureAvailable(feature: String, callback: (Result<Boolean>) -> Unit)
  /**
   * Reads records of [recordType] in the [startEpochMs, endEpochMs] window,
   * returning one JSON object (as a String) per record. [filterJson] is an
   * optional JSON object carrying extra read constraints (data origins,
   * paging, ascending/descending, page size, etc.).
   */
  fun readRecordsJson(recordType: String, startEpochMs: Long, endEpochMs: Long, filterJson: String?, callback: (Result<List<String>>) -> Unit)
  /**
   * Reads a single record of [recordType] by its Health Connect [recordId],
   * or `null` if it does not exist.
   */
  fun readRecordJson(recordType: String, recordId: String, callback: (Result<String?>) -> Unit)
  /**
   * Runs an aggregation over [aggregateMetrics] in the given window, returning
   * a metric-key -> value map (value is `null` when Health Connect has no data
   * for that metric in the window).
   */
  fun aggregate(aggregateMetrics: List<String>, startEpochMs: Long, endEpochMs: Long, callback: (Result<Map<String, Double?>>) -> Unit)
  /**
   * Aggregates [aggregateMetrics] grouped into buckets of [bucketType]
   * (e.g. `"DAYS"`, `"WEEKS"`, `"MONTHS"`), returning one JSON object (as a
   * String) per bucket with its time range and aggregated values.
   */
  fun aggregateGroupByPeriodJson(aggregateMetrics: List<String>, startEpochMs: Long, endEpochMs: Long, bucketType: String, callback: (Result<List<String>>) -> Unit)
  /**
   * Inserts the given records (each a JSON object String matching the canonical
   * schema) and returns the inserted Health Connect record ids in order.
   */
  fun insertRecordsJson(recordsJson: List<String>, callback: (Result<List<String>>) -> Unit)
  /** Deletes records of [recordType] by their app-assigned client record ids. */
  fun deleteRecordsByClientIds(recordType: String, clientRecordIds: List<String>, callback: (Result<Unit>) -> Unit)
  /** Deletes records of [recordType] by their Health Connect record ids. */
  fun deleteRecordsByIds(recordType: String, recordIds: List<String>, callback: (Result<Unit>) -> Unit)
  /**
   * Import dedup helper: of the supplied [clientRecordIds], returns the subset
   * that ALREADY exist in Health Connect for [recordType].
   */
  fun filterExistingClientIds(recordType: String, clientRecordIds: List<String>, callback: (Result<List<String>>) -> Unit)

  companion object {
    /** The codec used by HealthConnectHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `HealthConnectHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: HealthConnectHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.getSdkStatus$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getSdkStatus())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.getGrantedPermissions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val permissionsArg = args[0] as List<String>
            api.getGrantedPermissions(permissionsArg) { result: Result<List<String>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.requestPermissions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val permissionsArg = args[0] as List<String>
            api.requestPermissions(permissionsArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.isFeatureAvailable$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val featureArg = args[0] as String
            api.isFeatureAvailable(featureArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.readRecordsJson$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val recordTypeArg = args[0] as String
            val startEpochMsArg = args[1] as Long
            val endEpochMsArg = args[2] as Long
            val filterJsonArg = args[3] as String?
            api.readRecordsJson(recordTypeArg, startEpochMsArg, endEpochMsArg, filterJsonArg) { result: Result<List<String>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.readRecordJson$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val recordTypeArg = args[0] as String
            val recordIdArg = args[1] as String
            api.readRecordJson(recordTypeArg, recordIdArg) { result: Result<String?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.aggregate$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val aggregateMetricsArg = args[0] as List<String>
            val startEpochMsArg = args[1] as Long
            val endEpochMsArg = args[2] as Long
            api.aggregate(aggregateMetricsArg, startEpochMsArg, endEpochMsArg) { result: Result<Map<String, Double?>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.aggregateGroupByPeriodJson$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val aggregateMetricsArg = args[0] as List<String>
            val startEpochMsArg = args[1] as Long
            val endEpochMsArg = args[2] as Long
            val bucketTypeArg = args[3] as String
            api.aggregateGroupByPeriodJson(aggregateMetricsArg, startEpochMsArg, endEpochMsArg, bucketTypeArg) { result: Result<List<String>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.insertRecordsJson$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val recordsJsonArg = args[0] as List<String>
            api.insertRecordsJson(recordsJsonArg) { result: Result<List<String>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.deleteRecordsByClientIds$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val recordTypeArg = args[0] as String
            val clientRecordIdsArg = args[1] as List<String>
            api.deleteRecordsByClientIds(recordTypeArg, clientRecordIdsArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.deleteRecordsByIds$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val recordTypeArg = args[0] as String
            val recordIdsArg = args[1] as List<String>
            api.deleteRecordsByIds(recordTypeArg, recordIdsArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.filterExistingClientIds$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val recordTypeArg = args[0] as String
            val clientRecordIdsArg = args[1] as List<String>
            api.filterExistingClientIds(recordTypeArg, clientRecordIdsArg) { result: Result<List<String>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
