// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package tech.mmarca.openvitals.health_connect_native

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/**
 * Raw Health Connect availability signals, mapped to the Dart
 * `HealthConnectAvailability` enum on the Flutter side. Kept as separate
 * signals (rather than a native enum) so the enum stays a single source of
 * truth in Dart.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class HealthConnectAvailabilityDetail (
  /** Raw `HealthConnectClient.getSdkStatus` int. */
  val sdkStatus: Long,
  /**
   * True when running in a work/managed profile where Health Connect is
   * unsupported (Android 13+).
   */
  val unsupportedProfile: Boolean,
  /**
   * True when the standalone Health Connect APK is installed on Android 13-
   * but the Play Store is not (so it can never be updated).
   */
  val standaloneNeedsPlayStore: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): HealthConnectAvailabilityDetail {
      val sdkStatus = pigeonVar_list[0] as Long
      val unsupportedProfile = pigeonVar_list[1] as Boolean
      val standaloneNeedsPlayStore = pigeonVar_list[2] as Boolean
      return HealthConnectAvailabilityDetail(sdkStatus, unsupportedProfile, standaloneNeedsPlayStore)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      sdkStatus,
      unsupportedProfile,
      standaloneNeedsPlayStore,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as HealthConnectAvailabilityDetail
    return MessagesPigeonUtils.deepEquals(this.sdkStatus, other.sdkStatus) && MessagesPigeonUtils.deepEquals(this.unsupportedProfile, other.unsupportedProfile) && MessagesPigeonUtils.deepEquals(this.standaloneNeedsPlayStore, other.standaloneNeedsPlayStore)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.sdkStatus)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.unsupportedProfile)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.standaloneNeedsPlayStore)
    return result
  }
  override fun toString(): String {
    return "HealthConnectAvailabilityDetail(sdkStatus=$sdkStatus, unsupportedProfile=$unsupportedProfile, standaloneNeedsPlayStore=$standaloneNeedsPlayStore)"
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          HealthConnectAvailabilityDetail.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is HealthConnectAvailabilityDetail -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Host (Android/Kotlin) API surface backed by `HealthConnectClient`.
 *
 * All record payloads are JSON strings; see the record JSON schema in
 * `lib/health_connect_native.dart`. Permission strings are Health Connect
 * permission identifiers (e.g. `android.permission.health.READ_STEPS`).
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface HealthConnectHostApi {
  /**
   * Maps to `HealthConnectClient.getSdkStatus(context)`.
   *
   * Returns the raw SDK status int (e.g. `SDK_AVAILABLE`,
   * `SDK_UNAVAILABLE`, `SDK_UNAVAILABLE_PROVIDER_UPDATE_REQUIRED`).
   */
  fun getSdkStatus(): Long
  /**
   * Fuller availability picture than [getSdkStatus]: SDK status plus the
   * work-profile and standalone-needs-Play-Store overrides, so Dart can resolve
   * NOT_SUPPORTED / NEEDS_PLAY_STORE / NEEDS_PROVIDER_UPDATE / AVAILABLE.
   */
  fun availabilityDetail(): HealthConnectAvailabilityDetail
  /**
   * Mirrors the user's "pause Health Connect sync" toggle into the native
   * sync-gate. While disabled, reads short-circuit to empty and writes throw.
   */
  fun setSyncEnabled(enabled: Boolean)
  /** Returns the native sync-gate's current state. */
  fun getSyncEnabled(): Boolean
  /** Returns the subset of [permissions] currently granted. */
  fun getGrantedPermissions(permissions: List<String>, callback: (Result<List<String>>) -> Unit)
  /**
   * Launches the Health Connect permission contract via the Activity and
   * resolves to whether every requested permission ended up granted.
   */
  fun requestPermissions(permissions: List<String>, callback: (Result<Boolean>) -> Unit)
  /**
   * Opens the Health Connect page for this app (app-specific permission
   * management on Android 14+, falling back to Health Connect settings) so the
   * user can manually grant permissions the runtime dialog reports as
   * non-requestable (e.g. planned exercise, exercise routes, background/history
   * access). Returns whether a page was launched.
   */
  fun openHealthConnectSettings(callback: (Result<Boolean>) -> Unit)
  /**
   * Whether an optional Health Connect feature is available on this device,
   * e.g. `"SKIN_TEMPERATURE"`, `"MINDFULNESS_SESSION"`, `"PLANNED_EXERCISE"`.
   */
  fun isFeatureAvailable(feature: String, callback: (Result<Boolean>) -> Unit)
  /**
   * Reads records of [recordType] in the [startEpochMs, endEpochMs] window,
   * returning one JSON object (as a String) per record. [filterJson] is an
   * optional JSON object carrying extra read constraints (data origins,
   * paging, ascending/descending, page size, etc.).
   */
  fun readRecordsJson(recordType: String, startEpochMs: Long, endEpochMs: Long, filterJson: String?, callback: (Result<List<String>>) -> Unit)
  /**
   * Reads a single record of [recordType] by its Health Connect [recordId],
   * or `null` if it does not exist.
   */
  fun readRecordJson(recordType: String, recordId: String, callback: (Result<String?>) -> Unit)
  /**
   * Runs an aggregation over [aggregateMetrics] in the given window, returning
   * a metric-key -> value map (value is `null` when Health Connect has no data
   * for that metric in the window).
   */
  fun aggregate(aggregateMetrics: List<String>, startEpochMs: Long, endEpochMs: Long, callback: (Result<Map<String, Double?>>) -> Unit)
  /**
   * Aggregates [aggregateMetrics] grouped into buckets of [bucketType]
   * (e.g. `"DAYS"`, `"WEEKS"`, `"MONTHS"`), returning one JSON object (as a
   * String) per bucket with its time range and aggregated values.
   */
  fun aggregateGroupByPeriodJson(aggregateMetrics: List<String>, startEpochMs: Long, endEpochMs: Long, bucketType: String, callback: (Result<List<String>>) -> Unit)
  /**
   * Inserts the given records (each a JSON object String matching the canonical
   * schema) and returns the inserted Health Connect record ids in order.
   */
  fun insertRecordsJson(recordsJson: List<String>, callback: (Result<List<String>>) -> Unit)
  /** Deletes records of [recordType] by their app-assigned client record ids. */
  fun deleteRecordsByClientIds(recordType: String, clientRecordIds: List<String>, callback: (Result<Unit>) -> Unit)
  /** Deletes records of [recordType] by their Health Connect record ids. */
  fun deleteRecordsByIds(recordType: String, recordIds: List<String>, callback: (Result<Unit>) -> Unit)
  /**
   * Import dedup helper: of the supplied [clientRecordIds], returns the subset
   * that ALREADY exist in Health Connect for [recordType].
   */
  fun filterExistingClientIds(recordType: String, clientRecordIds: List<String>, callback: (Result<List<String>>) -> Unit)

  companion object {
    /** The codec used by HealthConnectHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `HealthConnectHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: HealthConnectHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.getSdkStatus$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getSdkStatus())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.availabilityDetail$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.availabilityDetail())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.setSyncEnabled$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val enabledArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.setSyncEnabled(enabledArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.getSyncEnabled$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getSyncEnabled())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.getGrantedPermissions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val permissionsArg = args[0] as List<String>
            api.getGrantedPermissions(permissionsArg) { result: Result<List<String>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.requestPermissions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val permissionsArg = args[0] as List<String>
            api.requestPermissions(permissionsArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.openHealthConnectSettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.openHealthConnectSettings{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.isFeatureAvailable$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val featureArg = args[0] as String
            api.isFeatureAvailable(featureArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.readRecordsJson$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val recordTypeArg = args[0] as String
            val startEpochMsArg = args[1] as Long
            val endEpochMsArg = args[2] as Long
            val filterJsonArg = args[3] as String?
            api.readRecordsJson(recordTypeArg, startEpochMsArg, endEpochMsArg, filterJsonArg) { result: Result<List<String>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.readRecordJson$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val recordTypeArg = args[0] as String
            val recordIdArg = args[1] as String
            api.readRecordJson(recordTypeArg, recordIdArg) { result: Result<String?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.aggregate$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val aggregateMetricsArg = args[0] as List<String>
            val startEpochMsArg = args[1] as Long
            val endEpochMsArg = args[2] as Long
            api.aggregate(aggregateMetricsArg, startEpochMsArg, endEpochMsArg) { result: Result<Map<String, Double?>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.aggregateGroupByPeriodJson$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val aggregateMetricsArg = args[0] as List<String>
            val startEpochMsArg = args[1] as Long
            val endEpochMsArg = args[2] as Long
            val bucketTypeArg = args[3] as String
            api.aggregateGroupByPeriodJson(aggregateMetricsArg, startEpochMsArg, endEpochMsArg, bucketTypeArg) { result: Result<List<String>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.insertRecordsJson$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val recordsJsonArg = args[0] as List<String>
            api.insertRecordsJson(recordsJsonArg) { result: Result<List<String>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.deleteRecordsByClientIds$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val recordTypeArg = args[0] as String
            val clientRecordIdsArg = args[1] as List<String>
            api.deleteRecordsByClientIds(recordTypeArg, clientRecordIdsArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.deleteRecordsByIds$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val recordTypeArg = args[0] as String
            val recordIdsArg = args[1] as List<String>
            api.deleteRecordsByIds(recordTypeArg, recordIdsArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.health_connect_native.HealthConnectHostApi.filterExistingClientIds$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val recordTypeArg = args[0] as String
            val clientRecordIdsArg = args[1] as List<String>
            api.filterExistingClientIds(recordTypeArg, clientRecordIdsArg) { result: Result<List<String>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
