import 'dart:convert';
import 'dart:io';

/// The shared fixture, in Dart.
///
/// `test/fixtures/health_connect/golden.json` is generated by
/// `tool/health_fixture/build.dart` from a real Health Connect export, and it is the
/// SAME file the Kotlin tier reads (Gradle puts it on that module's test classpath).
/// One fixture, two tiers: two copies would drift, and a drifted fixture is a suite
/// that is green about the wrong data.
///
/// Parsed once per test PROCESS, not once per test — 3,593 records is cheap to hold
/// and expensive to re-parse 200 times.
class HcFixture {
  HcFixture._(this._root);

  static HcFixture? _cached;

  static HcFixture load() => _cached ??= HcFixture._(
        jsonDecode(
          File('test/fixtures/health_connect/golden.json').readAsStringSync(),
        ) as Map<String, Object?>,
      );

  final Map<String, Object?> _root;

  Map<String, Object?> get manifest => _root['manifest']! as Map<String, Object?>;

  List<Map<String, Object?>> records(String kind) =>
      (_root[kind]! as List).cast<Map<String, Object?>>();

  // ── the scenarios, named so no test ever hardcodes a date ────────────────────

  /// The heart-rate record that swallows a workout — 17.48 hours of it.
  Map<String, Object?> get swallowingHeartRate => records('heartRate').reduce((a, b) =>
      _span(a) > _span(b) ? a : b);

  /// The exercise session that sits inside it, and whose heart rate read as empty.
  Map<String, Object?> get swallowedWorkout {
    final hr = swallowingHeartRate;
    return records('exercise').firstWhere((e) =>
        (e['start']! as int) >= (hr['start']! as int) &&
        (e['end']! as int) <= (hr['end']! as int));
  }

  /// The session with a GPS route — the long outdoor one, and the only one whose
  /// splits can be computed from real geometry.
  Map<String, Object?> get routeWorkout => records('exercise')
      .reduce((a, b) => (a['route']! as List).length >= (b['route']! as List).length
          ? a
          : b);

  /// A night with sleep from two different writers — the merge path.
  DateTime get multiWriterSleepNight {
    final byNight = <String, Set<String>>{};
    for (final s in records('sleep')) {
      final night = _day(s['start']! as int);
      byNight.putIfAbsent(night, () => {}).add(s['writer']! as String);
    }
    final night = byNight.entries.firstWhere((e) => e.value.length > 1).key;
    return DateTime.parse(night);
  }

  /// A day the fixture has no records for at all.
  ///
  /// "No data" and "zero" are different answers and several screens branch on the
  /// difference, so a day that is genuinely empty is a scenario, not an oversight.
  DateTime get emptyDay {
    final busy = <String>{
      for (final kind in ['heartRate', 'exercise', 'sleep', 'steps'])
        for (final r in records(kind)) _day(r['start']! as int),
    };
    var day = _dayOf(records('heartRate').first['start']! as int);
    for (var i = 0; i < 60; i++) {
      final candidate = day.add(Duration(days: i));
      if (!busy.contains(candidate.toIso8601String().substring(0, 10))) {
        return candidate;
      }
    }
    throw StateError('The fixture has no empty day — add one, or the "no data" '
        'branch is never exercised.');
  }

  static int _span(Map<String, Object?> r) =>
      (r['end']! as int) - (r['start']! as int);

  static String _day(int epochMs) =>
      _dayOf(epochMs).toIso8601String().substring(0, 10);

  static DateTime _dayOf(int epochMs) {
    final t = DateTime.fromMillisecondsSinceEpoch(epochMs, isUtc: true);
    return DateTime.utc(t.year, t.month, t.day);
  }
}
