package tech.mmarca.openvitals.healthconnect

import com.google.gson.Gson
import com.google.gson.JsonObject
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * The safety control. `golden.json` is derived from a real person's export and this repo
 * is public, so the fixture is checked on every run. The first fixture leaked twice: the
 * alias table's keys were the real package names, and an alias still named the vendor.
 */
class FixtureScrubTest {

    private val raw: String by lazy {
        FixtureScrubTest::class.java.classLoader!!
            .getResourceAsStream("golden.json")
            ?.reader()
            ?.readText()
            ?: error(
                "golden.json is not on the test classpath. It is generated by " +
                    "`python3 tool/health_fixture/build.py`; build.gradle adds it as a " +
                    "test resource.",
            )
    }

    private val fixture: JsonObject by lazy { Gson().fromJson(raw, JsonObject::class.java) }

    @Test
    fun `no real writer, vendor or person appears anywhere in the fixture`() {
        // Substrings, not whole package names.
        val denied = listOf(
            "gadgetbridge", "freeyourgadget", "nodomain",
            "garmin", "hevy", "technogym", "opentracks", "dennisguse",
            "tadris", "hydrotracker", "cemcakmak", "healthsync", "appyhapps",
            "homeassistant", "heartwood", "easonhuang", "monkopedia", "ot2hc",
            // The maintainer's own name appears in real package names (dev.manu.*).
            "manu",
        )

        val lowered = raw.lowercase()
        val found = denied.filter { lowered.contains(it) }

        assertTrue(
            "The fixture leaks real identifying strings into a PUBLIC repo, and git " +
                "history cannot un-commit them:\n  ${found.joinToString("\n  ")}\n" +
                "Fix tool/health_fixture/build.py and regenerate. Do NOT hand-edit the " +
                "fixture — the next regeneration would put it straight back.",
            found.isEmpty(),
        )
    }

    @Test
    fun `every writer is either an example alias or OpenVitals itself`() {
        // Fail closed: a writer the alias table has never heard of must not reach the file.
        val writers = fixture["manifest"].asJsonObject["writers"].asJsonArray.map { it.asString }

        writers.forEach { writer ->
            val allowed = writer.startsWith("com.example.") ||
                // Load-bearing: isOpenVitalsEntry, ownership, the manual-entry count.
                writer.startsWith("tech.mmarca.openvitals") ||
                // Health Connect's own platform writers. Not a person.
                writer == "android" ||
                writer == "com.android.shell"

            assertTrue(
                "\"$writer\" is neither an alias nor a platform writer. The aliasing " +
                    "in build.py failed open.",
                allowed,
            )
        }
    }

    @Test
    fun `no coordinate is anywhere near the real route`() {
        // The track is rotated and re-anchored to the North Sea. Shape, length and speed survive.
        fixture["exercise"].asJsonArray.forEach { session ->
            session.asJsonObject["route"].asJsonArray.forEach { point ->
                val lat = point.asJsonObject["lat"].asDouble
                val lon = point.asJsonObject["lon"].asDouble
                assertTrue(
                    "A route point ($lat, $lon) is outside the synthetic bbox — the " +
                        "GPS re-anchoring did not happen, and this is a real place " +
                        "someone was.",
                    lat in 55.0..57.0,
                )
                assertTrue("A route point ($lat, $lon) is outside the synthetic bbox", lon in 2.0..4.0)
            }
        }
    }

    @Test
    fun `no free text survived`() {
        // Titles and notes are the one field a human types into.
        val canned = setOf("Session", "Sleep", "Recorded by a device.", "Sleep data from a device.")

        listOf("exercise", "sleep").forEach { key ->
            fixture[key].asJsonArray.forEach { element ->
                val record = element.asJsonObject
                listOf("title", "notes").forEach { field ->
                    val value = record[field]?.takeIf { !it.isJsonNull }?.asString ?: return@forEach
                    assertTrue(
                        "$key.$field is \"$value\" — that is not one of the canned " +
                            "replacements, so a real note or title reached the fixture.",
                        canned.contains(value),
                    )
                }
            }
        }
    }
}
