package tech.mmarca.openvitals.healthconnect

import com.google.gson.Gson
import com.google.gson.JsonObject
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * The safety control, and the most important test in this repository.
 *
 * `golden.json` is DERIVED from a real person's Health Connect export — heart rate,
 * sleep, workouts, the lot — and this repo is PUBLIC. Git history is append-only: a
 * leak committed here cannot be taken back by a later commit. So the fixture is
 * checked on every run, not just on the day it was generated.
 *
 * It is not hypothetical. The first generated fixture leaked twice, and both were
 * caught here:
 *
 *  * the manifest embedded the writer ALIAS TABLE, whose *keys* are the real
 *    package names — the scrubber leaked its own key;
 *  * `com.example.healthsync` as an alias still told the world which apps this
 *    person runs, which is most of what the scrub is for.
 *
 * The Kotlin tier reads the very same file the Dart tier does (Gradle puts it on
 * this module's test classpath), so this guard has to run on both sides or the
 * fixture is only checked when someone happens to run the other suite.
 */
class FixtureScrubTest {

    private val raw: String by lazy {
        FixtureScrubTest::class.java.classLoader!!
            .getResourceAsStream("golden.json")
            ?.reader()
            ?.readText()
            ?: error(
                "golden.json is not on the test classpath. It is generated by " +
                    "`python3 tool/health_fixture/build.py`; build.gradle adds it as a " +
                    "test resource.",
            )
    }

    private val fixture: JsonObject by lazy { Gson().fromJson(raw, JsonObject::class.java) }

    @Test
    fun `no real writer, vendor or person appears anywhere in the fixture`() {
        // Substrings, not whole package names: an alias that merely *contains* the
        // vendor ("com.example.healthsync") is not an alias.
        val denied = listOf(
            "gadgetbridge", "freeyourgadget", "nodomain",
            "garmin", "hevy", "technogym", "opentracks", "dennisguse",
            "tadris", "hydrotracker", "cemcakmak", "healthsync", "appyhapps",
            "homeassistant", "heartwood", "easonhuang", "monkopedia", "ot2hc",
            // The maintainer's own name appears in real package names (dev.manu.*).
            "manu",
        )

        val lowered = raw.lowercase()
        val found = denied.filter { lowered.contains(it) }

        assertTrue(
            "The fixture leaks real identifying strings into a PUBLIC repo, and git " +
                "history cannot un-commit them:\n  ${found.joinToString("\n  ")}\n" +
                "Fix tool/health_fixture/build.py and regenerate. Do NOT hand-edit the " +
                "fixture — the next regeneration would put it straight back.",
            found.isEmpty(),
        )
    }

    @Test
    fun `every writer is either an example alias or OpenVitals itself`() {
        // Fail CLOSED. A writer the alias table has never heard of must not be able
        // to reach the file just because nobody thought about it.
        val writers = fixture["manifest"].asJsonObject["writers"].asJsonArray.map { it.asString }

        writers.forEach { writer ->
            val allowed = writer.startsWith("com.example.") ||
                // Load-bearing: isOpenVitalsEntry, ownership, the manual-entry count.
                writer.startsWith("tech.mmarca.openvitals") ||
                // Health Connect's own platform writers. Not a person.
                writer == "android" ||
                writer == "com.android.shell"

            assertTrue(
                "\"$writer\" is neither an alias nor a platform writer. The aliasing " +
                    "in build.py failed open.",
                allowed,
            )
        }
    }

    @Test
    fun `no coordinate is anywhere near the real route`() {
        // The track is rotated and re-anchored to a synthetic origin in the North
        // Sea. Shape, length and speed profile survive — so distance, pace and
        // splits are genuinely exercised — but the location does not.
        fixture["exercise"].asJsonArray.forEach { session ->
            session.asJsonObject["route"].asJsonArray.forEach { point ->
                val lat = point.asJsonObject["lat"].asDouble
                val lon = point.asJsonObject["lon"].asDouble
                assertTrue(
                    "A route point ($lat, $lon) is outside the synthetic bbox — the " +
                        "GPS re-anchoring did not happen, and this is a real place " +
                        "someone was.",
                    lat in 55.0..57.0,
                )
                assertTrue("A route point ($lat, $lon) is outside the synthetic bbox", lon in 2.0..4.0)
            }
        }
    }

    @Test
    fun `no free text survived`() {
        // Titles and notes are the one field a human types into. Never carry one
        // across.
        val canned = setOf("Session", "Sleep", "Recorded by a device.", "Sleep data from a device.")

        listOf("exercise", "sleep").forEach { key ->
            fixture[key].asJsonArray.forEach { element ->
                val record = element.asJsonObject
                listOf("title", "notes").forEach { field ->
                    val value = record[field]?.takeIf { !it.isJsonNull }?.asString ?: return@forEach
                    assertTrue(
                        "$key.$field is \"$value\" — that is not one of the canned " +
                            "replacements, so a real note or title reached the fixture.",
                        canned.contains(value),
                    )
                }
            }
        }
    }
}
